//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuery.AdgroupService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v3", ConfigurationName="AdgroupService.AdgroupService")]
    public interface AdgroupService {
        
        // CODEGEN: 消息 getAdgroupIdByCampaignIdRequest 的包装名称(getAdgroupIdByCampaignIdRequest)以后生成的消息协定与默认值(getAdgroupIdByCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAdgroupIdByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.getAdgroupIdByCampaignIdResponse getAdgroupIdByCampaignId(WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAdgroupIdByCampaignId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupIdByCampaignIdResponse> getAdgroupIdByCampaignIdAsync(WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest request);
        
        // CODEGEN: 消息 getAllAdgroupIdRequest 的包装名称(getAllAdgroupIdRequest)以后生成的消息协定与默认值(getAllAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAllAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.getAllAdgroupIdResponse getAllAdgroupId(WpfQuery.AdgroupService.getAllAdgroupIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAllAdgroupId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAllAdgroupIdResponse> getAllAdgroupIdAsync(WpfQuery.AdgroupService.getAllAdgroupIdRequest request);
        
        // CODEGEN: 消息 getAdgroupByCampaignIdRequest 的包装名称(getAdgroupByCampaignIdRequest)以后生成的消息协定与默认值(getAdgroupByCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAdgroupByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.getAdgroupByCampaignIdResponse getAdgroupByCampaignId(WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAdgroupByCampaignId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupByCampaignIdResponse> getAdgroupByCampaignIdAsync(WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest request);
        
        // CODEGEN: 消息 getAdgroupByAdgroupIdRequest 的包装名称(getAdgroupByAdgroupIdRequest)以后生成的消息协定与默认值(getAdgroupByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAdgroupByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.getAdgroupByAdgroupIdResponse getAdgroupByAdgroupId(WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/getAdgroupByAdgroupId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupByAdgroupIdResponse> getAdgroupByAdgroupIdAsync(WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/addAdgroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.addAdgroupResponse addAdgroup(WpfQuery.AdgroupService.addAdgroupRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/addAdgroup", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.addAdgroupResponse> addAdgroupAsync(WpfQuery.AdgroupService.addAdgroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/updateAdgroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.updateAdgroupResponse updateAdgroup(WpfQuery.AdgroupService.updateAdgroupRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/updateAdgroup", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.updateAdgroupResponse> updateAdgroupAsync(WpfQuery.AdgroupService.updateAdgroupRequest request);
        
        // CODEGEN: 消息 deleteAdgroupRequest 的包装名称(deleteAdgroupRequest)以后生成的消息协定与默认值(deleteAdgroup)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/deleteAdgroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.AdgroupService.deleteAdgroupResponse deleteAdgroup(WpfQuery.AdgroupService.deleteAdgroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/AdgroupService/deleteAdgroup", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.deleteAdgroupResponse> deleteAdgroupAsync(WpfQuery.AdgroupService.deleteAdgroupRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        private string actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class DoubleMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class FloatMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class LongMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class IntMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class StringMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class OptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringMapItemType[] optStringField;
        
        private IntMapItemType[] optIntField;
        
        private LongMapItemType[] optLongField;
        
        private FloatMapItemType[] optFloatField;
        
        private DoubleMapItemType[] optDoubleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optString", Order=0)]
        public StringMapItemType[] optString {
            get {
                return this.optStringField;
            }
            set {
                this.optStringField = value;
                this.RaisePropertyChanged("optString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optInt", Order=1)]
        public IntMapItemType[] optInt {
            get {
                return this.optIntField;
            }
            set {
                this.optIntField = value;
                this.RaisePropertyChanged("optInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optLong", Order=2)]
        public LongMapItemType[] optLong {
            get {
                return this.optLongField;
            }
            set {
                this.optLongField = value;
                this.RaisePropertyChanged("optLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optFloat", Order=3)]
        public FloatMapItemType[] optFloat {
            get {
                return this.optFloatField;
            }
            set {
                this.optFloatField = value;
                this.RaisePropertyChanged("optFloat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optDouble", Order=4)]
        public DoubleMapItemType[] optDouble {
            get {
                return this.optDoubleField;
            }
            set {
                this.optDoubleField = value;
                this.RaisePropertyChanged("optDouble");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class AdgroupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private long campaignIdField;
        
        private bool campaignIdFieldSpecified;
        
        private string adgroupNameField;
        
        private double maxPriceField;
        
        private bool maxPriceFieldSpecified;
        
        private string[] negativeWordsField;
        
        private string[] exactNegativeWordsField;
        
        private string reservedField;
        
        private bool pauseField;
        
        private bool pauseFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool campaignIdSpecified {
            get {
                return this.campaignIdFieldSpecified;
            }
            set {
                this.campaignIdFieldSpecified = value;
                this.RaisePropertyChanged("campaignIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string adgroupName {
            get {
                return this.adgroupNameField;
            }
            set {
                this.adgroupNameField = value;
                this.RaisePropertyChanged("adgroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double maxPrice {
            get {
                return this.maxPriceField;
            }
            set {
                this.maxPriceField = value;
                this.RaisePropertyChanged("maxPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPriceSpecified {
            get {
                return this.maxPriceFieldSpecified;
            }
            set {
                this.maxPriceFieldSpecified = value;
                this.RaisePropertyChanged("maxPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("negativeWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string[] negativeWords {
            get {
                return this.negativeWordsField;
            }
            set {
                this.negativeWordsField = value;
                this.RaisePropertyChanged("negativeWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exactNegativeWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string[] exactNegativeWords {
            get {
                return this.exactNegativeWordsField;
            }
            set {
                this.exactNegativeWordsField = value;
                this.RaisePropertyChanged("exactNegativeWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
                this.RaisePropertyChanged("reserved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool pause {
            get {
                return this.pauseField;
            }
            set {
                this.pauseField = value;
                this.RaisePropertyChanged("pause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pauseSpecified {
            get {
                return this.pauseFieldSpecified;
            }
            set {
                this.pauseFieldSpecified = value;
                this.RaisePropertyChanged("pauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.baidu.com/sem/common/v2", Order=9)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class CampaignAdgroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long campaignIdField;
        
        private AdgroupType[] adgroupTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adgroupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public AdgroupType[] adgroupTypes {
            get {
                return this.adgroupTypesField;
            }
            set {
                this.adgroupTypesField = value;
                this.RaisePropertyChanged("adgroupTypes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class CampaignAdgroupId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long campaignIdField;
        
        private long[] adgroupIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long[] adgroupIds {
            get {
                return this.adgroupIdsField;
            }
            set {
                this.adgroupIdsField = value;
                this.RaisePropertyChanged("adgroupIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdgroupIdByCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdgroupIdByCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getAdgroupIdByCampaignIdRequest() {
        }
        
        public getAdgroupIdByCampaignIdRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] campaignIds) {
            this.AuthHeader = AuthHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdgroupIdByCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdgroupIdByCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignAdgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.CampaignAdgroupId[] campaignAdgroupIds;
        
        public getAdgroupIdByCampaignIdResponse() {
        }
        
        public getAdgroupIdByCampaignIdResponse(WpfQuery.AdgroupService.ResHeader ResHeader, WpfQuery.AdgroupService.CampaignAdgroupId[] campaignAdgroupIds) {
            this.ResHeader = ResHeader;
            this.campaignAdgroupIds = campaignAdgroupIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAllAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        public getAllAdgroupIdRequest() {
        }
        
        public getAllAdgroupIdRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAllAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignAdgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.CampaignAdgroupId[] campaignAdgroupIds;
        
        public getAllAdgroupIdResponse() {
        }
        
        public getAllAdgroupIdResponse(WpfQuery.AdgroupService.ResHeader ResHeader, WpfQuery.AdgroupService.CampaignAdgroupId[] campaignAdgroupIds) {
            this.ResHeader = ResHeader;
            this.campaignAdgroupIds = campaignAdgroupIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdgroupByCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdgroupByCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getAdgroupByCampaignIdRequest() {
        }
        
        public getAdgroupByCampaignIdRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] campaignIds) {
            this.AuthHeader = AuthHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdgroupByCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdgroupByCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignAdgroups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.CampaignAdgroup[] campaignAdgroups;
        
        public getAdgroupByCampaignIdResponse() {
        }
        
        public getAdgroupByCampaignIdResponse(WpfQuery.AdgroupService.ResHeader ResHeader, WpfQuery.AdgroupService.CampaignAdgroup[] campaignAdgroups) {
            this.ResHeader = ResHeader;
            this.campaignAdgroups = campaignAdgroups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdgroupByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdgroupByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        public getAdgroupByAdgroupIdRequest() {
        }
        
        public getAdgroupByAdgroupIdRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] adgroupIds) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdgroupByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdgroupByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.AdgroupType[] adgroupTypes;
        
        public getAdgroupByAdgroupIdResponse() {
        }
        
        public getAdgroupByAdgroupIdResponse(WpfQuery.AdgroupService.ResHeader ResHeader, WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            this.ResHeader = ResHeader;
            this.adgroupTypes = adgroupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdgroupRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class addAdgroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.AdgroupType[] adgroupTypes;
        
        public addAdgroupRequest() {
        }
        
        public addAdgroupRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader, WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            this.AuthHeader = AuthHeader;
            this.adgroupTypes = adgroupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdgroupResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class addAdgroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.AdgroupType[] adgroupTypes;
        
        public addAdgroupResponse() {
        }
        
        public addAdgroupResponse(WpfQuery.AdgroupService.ResHeader ResHeader, WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            this.ResHeader = ResHeader;
            this.adgroupTypes = adgroupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateAdgroupRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class updateAdgroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.AdgroupType[] adgroupTypes;
        
        public updateAdgroupRequest() {
        }
        
        public updateAdgroupRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader, WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            this.AuthHeader = AuthHeader;
            this.adgroupTypes = adgroupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateAdgroupResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class updateAdgroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.AdgroupService.AdgroupType[] adgroupTypes;
        
        public updateAdgroupResponse() {
        }
        
        public updateAdgroupResponse(WpfQuery.AdgroupService.ResHeader ResHeader, WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            this.ResHeader = ResHeader;
            this.adgroupTypes = adgroupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAdgroupRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class deleteAdgroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        public deleteAdgroupRequest() {
        }
        
        public deleteAdgroupRequest(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] adgroupIds) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAdgroupResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class deleteAdgroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.AdgroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public deleteAdgroupResponse() {
        }
        
        public deleteAdgroupResponse(WpfQuery.AdgroupService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdgroupServiceChannel : WpfQuery.AdgroupService.AdgroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdgroupServiceClient : System.ServiceModel.ClientBase<WpfQuery.AdgroupService.AdgroupService>, WpfQuery.AdgroupService.AdgroupService {
        
        public AdgroupServiceClient() {
        }
        
        public AdgroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdgroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdgroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdgroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.getAdgroupIdByCampaignIdResponse WpfQuery.AdgroupService.AdgroupService.getAdgroupIdByCampaignId(WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest request) {
            return base.Channel.getAdgroupIdByCampaignId(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader getAdgroupIdByCampaignId(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] campaignIds, out WpfQuery.AdgroupService.CampaignAdgroupId[] campaignAdgroupIds) {
            WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest inValue = new WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            WpfQuery.AdgroupService.getAdgroupIdByCampaignIdResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).getAdgroupIdByCampaignId(inValue);
            campaignAdgroupIds = retVal.campaignAdgroupIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupIdByCampaignIdResponse> WpfQuery.AdgroupService.AdgroupService.getAdgroupIdByCampaignIdAsync(WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest request) {
            return base.Channel.getAdgroupIdByCampaignIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupIdByCampaignIdResponse> getAdgroupIdByCampaignIdAsync(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] campaignIds) {
            WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest inValue = new WpfQuery.AdgroupService.getAdgroupIdByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            return ((WpfQuery.AdgroupService.AdgroupService)(this)).getAdgroupIdByCampaignIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.getAllAdgroupIdResponse WpfQuery.AdgroupService.AdgroupService.getAllAdgroupId(WpfQuery.AdgroupService.getAllAdgroupIdRequest request) {
            return base.Channel.getAllAdgroupId(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader getAllAdgroupId(WpfQuery.AdgroupService.AuthHeader AuthHeader, out WpfQuery.AdgroupService.CampaignAdgroupId[] campaignAdgroupIds) {
            WpfQuery.AdgroupService.getAllAdgroupIdRequest inValue = new WpfQuery.AdgroupService.getAllAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            WpfQuery.AdgroupService.getAllAdgroupIdResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).getAllAdgroupId(inValue);
            campaignAdgroupIds = retVal.campaignAdgroupIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAllAdgroupIdResponse> WpfQuery.AdgroupService.AdgroupService.getAllAdgroupIdAsync(WpfQuery.AdgroupService.getAllAdgroupIdRequest request) {
            return base.Channel.getAllAdgroupIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAllAdgroupIdResponse> getAllAdgroupIdAsync(WpfQuery.AdgroupService.AuthHeader AuthHeader) {
            WpfQuery.AdgroupService.getAllAdgroupIdRequest inValue = new WpfQuery.AdgroupService.getAllAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            return ((WpfQuery.AdgroupService.AdgroupService)(this)).getAllAdgroupIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.getAdgroupByCampaignIdResponse WpfQuery.AdgroupService.AdgroupService.getAdgroupByCampaignId(WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest request) {
            return base.Channel.getAdgroupByCampaignId(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader getAdgroupByCampaignId(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] campaignIds, out WpfQuery.AdgroupService.CampaignAdgroup[] campaignAdgroups) {
            WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest inValue = new WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            WpfQuery.AdgroupService.getAdgroupByCampaignIdResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).getAdgroupByCampaignId(inValue);
            campaignAdgroups = retVal.campaignAdgroups;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupByCampaignIdResponse> WpfQuery.AdgroupService.AdgroupService.getAdgroupByCampaignIdAsync(WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest request) {
            return base.Channel.getAdgroupByCampaignIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupByCampaignIdResponse> getAdgroupByCampaignIdAsync(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] campaignIds) {
            WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest inValue = new WpfQuery.AdgroupService.getAdgroupByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            return ((WpfQuery.AdgroupService.AdgroupService)(this)).getAdgroupByCampaignIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.getAdgroupByAdgroupIdResponse WpfQuery.AdgroupService.AdgroupService.getAdgroupByAdgroupId(WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest request) {
            return base.Channel.getAdgroupByAdgroupId(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader getAdgroupByAdgroupId(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] adgroupIds, out WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest inValue = new WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            WpfQuery.AdgroupService.getAdgroupByAdgroupIdResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).getAdgroupByAdgroupId(inValue);
            adgroupTypes = retVal.adgroupTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupByAdgroupIdResponse> WpfQuery.AdgroupService.AdgroupService.getAdgroupByAdgroupIdAsync(WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest request) {
            return base.Channel.getAdgroupByAdgroupIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.getAdgroupByAdgroupIdResponse> getAdgroupByAdgroupIdAsync(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] adgroupIds) {
            WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest inValue = new WpfQuery.AdgroupService.getAdgroupByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            return ((WpfQuery.AdgroupService.AdgroupService)(this)).getAdgroupByAdgroupIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.addAdgroupResponse WpfQuery.AdgroupService.AdgroupService.addAdgroup(WpfQuery.AdgroupService.addAdgroupRequest request) {
            return base.Channel.addAdgroup(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader addAdgroup(WpfQuery.AdgroupService.AuthHeader AuthHeader, ref WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            WpfQuery.AdgroupService.addAdgroupRequest inValue = new WpfQuery.AdgroupService.addAdgroupRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupTypes = adgroupTypes;
            WpfQuery.AdgroupService.addAdgroupResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).addAdgroup(inValue);
            adgroupTypes = retVal.adgroupTypes;
            return retVal.ResHeader;
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.addAdgroupResponse> addAdgroupAsync(WpfQuery.AdgroupService.addAdgroupRequest request) {
            return base.Channel.addAdgroupAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.updateAdgroupResponse WpfQuery.AdgroupService.AdgroupService.updateAdgroup(WpfQuery.AdgroupService.updateAdgroupRequest request) {
            return base.Channel.updateAdgroup(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader updateAdgroup(WpfQuery.AdgroupService.AuthHeader AuthHeader, ref WpfQuery.AdgroupService.AdgroupType[] adgroupTypes) {
            WpfQuery.AdgroupService.updateAdgroupRequest inValue = new WpfQuery.AdgroupService.updateAdgroupRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupTypes = adgroupTypes;
            WpfQuery.AdgroupService.updateAdgroupResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).updateAdgroup(inValue);
            adgroupTypes = retVal.adgroupTypes;
            return retVal.ResHeader;
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.updateAdgroupResponse> updateAdgroupAsync(WpfQuery.AdgroupService.updateAdgroupRequest request) {
            return base.Channel.updateAdgroupAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.AdgroupService.deleteAdgroupResponse WpfQuery.AdgroupService.AdgroupService.deleteAdgroup(WpfQuery.AdgroupService.deleteAdgroupRequest request) {
            return base.Channel.deleteAdgroup(request);
        }
        
        public WpfQuery.AdgroupService.ResHeader deleteAdgroup(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] adgroupIds, out string response) {
            WpfQuery.AdgroupService.deleteAdgroupRequest inValue = new WpfQuery.AdgroupService.deleteAdgroupRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            WpfQuery.AdgroupService.deleteAdgroupResponse retVal = ((WpfQuery.AdgroupService.AdgroupService)(this)).deleteAdgroup(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.AdgroupService.deleteAdgroupResponse> WpfQuery.AdgroupService.AdgroupService.deleteAdgroupAsync(WpfQuery.AdgroupService.deleteAdgroupRequest request) {
            return base.Channel.deleteAdgroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.AdgroupService.deleteAdgroupResponse> deleteAdgroupAsync(WpfQuery.AdgroupService.AuthHeader AuthHeader, long[] adgroupIds) {
            WpfQuery.AdgroupService.deleteAdgroupRequest inValue = new WpfQuery.AdgroupService.deleteAdgroupRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            return ((WpfQuery.AdgroupService.AdgroupService)(this)).deleteAdgroupAsync(inValue);
        }
    }
}
