//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuery.BDWMKRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="BDWMKRService.KRService")]
    public interface KRService {
        
        // CODEGEN: 消息 getKRBySeedRequest 的包装名称(getKRBySeedRequest)以后生成的消息协定与默认值(getKRBySeed)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/KRService/getKRBySeed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.BDWMKRService.getKRBySeedResponse getKRBySeed(WpfQuery.BDWMKRService.getKRBySeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/KRService/getKRBySeed", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRBySeedResponse> getKRBySeedAsync(WpfQuery.BDWMKRService.getKRBySeedRequest request);
        
        // CODEGEN: 消息 getKRSuggestBySeedRequest 的包装名称(GetKRSuggestBySeedRequest)以后生成的消息协定与默认值(getKRSuggestBySeed)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/KRService/getKRSuggestBySeed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.BDWMKRService.getKRSuggestBySeedResponse getKRSuggestBySeed(WpfQuery.BDWMKRService.getKRSuggestBySeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/KRService/getKRSuggestBySeed", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRSuggestBySeedResponse> getKRSuggestBySeedAsync(WpfQuery.BDWMKRService.getKRSuggestBySeedRequest request);
        
        // CODEGEN: 消息 getKRAndSuggestBySeedRequest 的包装名称(getKRAndSuggestBySeedRequest)以后生成的消息协定与默认值(getKRAndSuggestBySeed)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/KRService/getKRAndSuggestBySeed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.BDWMKRService.getKRAndSuggestBySeedResponse getKRAndSuggestBySeed(WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/KRService/getKRAndSuggestBySeed", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRAndSuggestBySeedResponse> getKRAndSuggestBySeedAsync(WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        private string actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class RelatedWordVo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string relatedWordField;
        
        private int reserved1Field;
        
        private bool reserved1FieldSpecified;
        
        private string reserved2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string relatedWord {
            get {
                return this.relatedWordField;
            }
            set {
                this.relatedWordField = value;
                this.RaisePropertyChanged("relatedWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int reserved1 {
            get {
                return this.reserved1Field;
            }
            set {
                this.reserved1Field = value;
                this.RaisePropertyChanged("reserved1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserved1Specified {
            get {
                return this.reserved1FieldSpecified;
            }
            set {
                this.reserved1FieldSpecified = value;
                this.RaisePropertyChanged("reserved1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string reserved2 {
            get {
                return this.reserved2Field;
            }
            set {
                this.reserved2Field = value;
                this.RaisePropertyChanged("reserved2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class RecommWordVo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private long avgShowCntField;
        
        private bool avgShowCntFieldSpecified;
        
        private long uvField;
        
        private bool uvFieldSpecified;
        
        private int cmpDegreeField;
        
        private bool cmpDegreeFieldSpecified;
        
        private string kwRootField;
        
        private long reasonIdField;
        
        private bool reasonIdFieldSpecified;
        
        private int reserved1Field;
        
        private bool reserved1FieldSpecified;
        
        private string reserved2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long avgShowCnt {
            get {
                return this.avgShowCntField;
            }
            set {
                this.avgShowCntField = value;
                this.RaisePropertyChanged("avgShowCnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avgShowCntSpecified {
            get {
                return this.avgShowCntFieldSpecified;
            }
            set {
                this.avgShowCntFieldSpecified = value;
                this.RaisePropertyChanged("avgShowCntSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long uv {
            get {
                return this.uvField;
            }
            set {
                this.uvField = value;
                this.RaisePropertyChanged("uv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uvSpecified {
            get {
                return this.uvFieldSpecified;
            }
            set {
                this.uvFieldSpecified = value;
                this.RaisePropertyChanged("uvSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cmpDegree {
            get {
                return this.cmpDegreeField;
            }
            set {
                this.cmpDegreeField = value;
                this.RaisePropertyChanged("cmpDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cmpDegreeSpecified {
            get {
                return this.cmpDegreeFieldSpecified;
            }
            set {
                this.cmpDegreeFieldSpecified = value;
                this.RaisePropertyChanged("cmpDegreeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string kwRoot {
            get {
                return this.kwRootField;
            }
            set {
                this.kwRootField = value;
                this.RaisePropertyChanged("kwRoot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long reasonId {
            get {
                return this.reasonIdField;
            }
            set {
                this.reasonIdField = value;
                this.RaisePropertyChanged("reasonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonIdSpecified {
            get {
                return this.reasonIdFieldSpecified;
            }
            set {
                this.reasonIdFieldSpecified = value;
                this.RaisePropertyChanged("reasonIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int reserved1 {
            get {
                return this.reserved1Field;
            }
            set {
                this.reserved1Field = value;
                this.RaisePropertyChanged("reserved1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserved1Specified {
            get {
                return this.reserved1FieldSpecified;
            }
            set {
                this.reserved1FieldSpecified = value;
                this.RaisePropertyChanged("reserved1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string reserved2 {
            get {
                return this.reserved2Field;
            }
            set {
                this.reserved2Field = value;
                this.RaisePropertyChanged("reserved2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class KRResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RecommWordVo[] recommWordVosField;
        
        private RelatedWordVo[] relatedWordVosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recommWordVos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RecommWordVo[] recommWordVos {
            get {
                return this.recommWordVosField;
            }
            set {
                this.recommWordVosField = value;
                this.RaisePropertyChanged("recommWordVos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatedWordVos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RelatedWordVo[] relatedWordVos {
            get {
                return this.relatedWordVosField;
            }
            set {
                this.relatedWordVosField = value;
                this.RaisePropertyChanged("relatedWordVos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class KRSuggestResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private string reservedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
                this.RaisePropertyChanged("reserved");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class KRResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private int avgShowCntField;
        
        private bool avgShowCntFieldSpecified;
        
        private int uvField;
        
        private bool uvFieldSpecified;
        
        private int cmpDegreeField;
        
        private bool cmpDegreeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int avgShowCnt {
            get {
                return this.avgShowCntField;
            }
            set {
                this.avgShowCntField = value;
                this.RaisePropertyChanged("avgShowCnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avgShowCntSpecified {
            get {
                return this.avgShowCntFieldSpecified;
            }
            set {
                this.avgShowCntFieldSpecified = value;
                this.RaisePropertyChanged("avgShowCntSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int uv {
            get {
                return this.uvField;
            }
            set {
                this.uvField = value;
                this.RaisePropertyChanged("uv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uvSpecified {
            get {
                return this.uvFieldSpecified;
            }
            set {
                this.uvFieldSpecified = value;
                this.RaisePropertyChanged("uvSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int cmpDegree {
            get {
                return this.cmpDegreeField;
            }
            set {
                this.cmpDegreeField = value;
                this.RaisePropertyChanged("cmpDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cmpDegreeSpecified {
            get {
                return this.cmpDegreeFieldSpecified;
            }
            set {
                this.cmpDegreeFieldSpecified = value;
                this.RaisePropertyChanged("cmpDegreeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRBySeedRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getKRBySeedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.BDWMKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long groupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("regionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] regionList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int targetType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int aliveDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("packIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] packIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reserved;
        
        public getKRBySeedRequest() {
        }
        
        public getKRBySeedRequest(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved) {
            this.AuthHeader = AuthHeader;
            this.seed = seed;
            this.groupId = groupId;
            this.regionList = regionList;
            this.targetType = targetType;
            this.aliveDays = aliveDays;
            this.packIds = packIds;
            this.reserved = reserved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRBySeedResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getKRBySeedResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.BDWMKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResultTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.BDWMKRService.KRResultType[] krResultTypes;
        
        public getKRBySeedResponse() {
        }
        
        public getKRBySeedResponse(WpfQuery.BDWMKRService.ResHeader ResHeader, WpfQuery.BDWMKRService.KRResultType[] krResultTypes) {
            this.ResHeader = ResHeader;
            this.krResultTypes = krResultTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKRSuggestBySeedRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getKRSuggestBySeedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.BDWMKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long groupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("regionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] regionList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int targetType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int aliveDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("packIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] packIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reserved;
        
        public getKRSuggestBySeedRequest() {
        }
        
        public getKRSuggestBySeedRequest(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved) {
            this.AuthHeader = AuthHeader;
            this.seed = seed;
            this.groupId = groupId;
            this.regionList = regionList;
            this.targetType = targetType;
            this.aliveDays = aliveDays;
            this.packIds = packIds;
            this.reserved = reserved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKRSuggestBySeedResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getKRSuggestBySeedResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.BDWMKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krSuggestResultTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.BDWMKRService.KRSuggestResultType[] krSuggestResultTypes;
        
        public getKRSuggestBySeedResponse() {
        }
        
        public getKRSuggestBySeedResponse(WpfQuery.BDWMKRService.ResHeader ResHeader, WpfQuery.BDWMKRService.KRSuggestResultType[] krSuggestResultTypes) {
            this.ResHeader = ResHeader;
            this.krSuggestResultTypes = krSuggestResultTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRAndSuggestBySeedRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getKRAndSuggestBySeedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.BDWMKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long groupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("regionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] regionList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int targetType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int aliveDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("packIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] packIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reserved;
        
        public getKRAndSuggestBySeedRequest() {
        }
        
        public getKRAndSuggestBySeedRequest(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved) {
            this.AuthHeader = AuthHeader;
            this.seed = seed;
            this.groupId = groupId;
            this.regionList = regionList;
            this.targetType = targetType;
            this.aliveDays = aliveDays;
            this.packIds = packIds;
            this.reserved = reserved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRAndSuggestBySeedResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getKRAndSuggestBySeedResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.BDWMKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResponses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.BDWMKRService.KRResponse[] krResponses;
        
        public getKRAndSuggestBySeedResponse() {
        }
        
        public getKRAndSuggestBySeedResponse(WpfQuery.BDWMKRService.ResHeader ResHeader, WpfQuery.BDWMKRService.KRResponse[] krResponses) {
            this.ResHeader = ResHeader;
            this.krResponses = krResponses;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KRServiceChannel : WpfQuery.BDWMKRService.KRService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KRServiceClient : System.ServiceModel.ClientBase<WpfQuery.BDWMKRService.KRService>, WpfQuery.BDWMKRService.KRService {
        
        public KRServiceClient() {
        }
        
        public KRServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KRServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KRServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.BDWMKRService.getKRBySeedResponse WpfQuery.BDWMKRService.KRService.getKRBySeed(WpfQuery.BDWMKRService.getKRBySeedRequest request) {
            return base.Channel.getKRBySeed(request);
        }
        
        public WpfQuery.BDWMKRService.ResHeader getKRBySeed(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved, out WpfQuery.BDWMKRService.KRResultType[] krResultTypes) {
            WpfQuery.BDWMKRService.getKRBySeedRequest inValue = new WpfQuery.BDWMKRService.getKRBySeedRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seed = seed;
            inValue.groupId = groupId;
            inValue.regionList = regionList;
            inValue.targetType = targetType;
            inValue.aliveDays = aliveDays;
            inValue.packIds = packIds;
            inValue.reserved = reserved;
            WpfQuery.BDWMKRService.getKRBySeedResponse retVal = ((WpfQuery.BDWMKRService.KRService)(this)).getKRBySeed(inValue);
            krResultTypes = retVal.krResultTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRBySeedResponse> WpfQuery.BDWMKRService.KRService.getKRBySeedAsync(WpfQuery.BDWMKRService.getKRBySeedRequest request) {
            return base.Channel.getKRBySeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRBySeedResponse> getKRBySeedAsync(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved) {
            WpfQuery.BDWMKRService.getKRBySeedRequest inValue = new WpfQuery.BDWMKRService.getKRBySeedRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seed = seed;
            inValue.groupId = groupId;
            inValue.regionList = regionList;
            inValue.targetType = targetType;
            inValue.aliveDays = aliveDays;
            inValue.packIds = packIds;
            inValue.reserved = reserved;
            return ((WpfQuery.BDWMKRService.KRService)(this)).getKRBySeedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.BDWMKRService.getKRSuggestBySeedResponse WpfQuery.BDWMKRService.KRService.getKRSuggestBySeed(WpfQuery.BDWMKRService.getKRSuggestBySeedRequest request) {
            return base.Channel.getKRSuggestBySeed(request);
        }
        
        public WpfQuery.BDWMKRService.ResHeader getKRSuggestBySeed(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved, out WpfQuery.BDWMKRService.KRSuggestResultType[] krSuggestResultTypes) {
            WpfQuery.BDWMKRService.getKRSuggestBySeedRequest inValue = new WpfQuery.BDWMKRService.getKRSuggestBySeedRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seed = seed;
            inValue.groupId = groupId;
            inValue.regionList = regionList;
            inValue.targetType = targetType;
            inValue.aliveDays = aliveDays;
            inValue.packIds = packIds;
            inValue.reserved = reserved;
            WpfQuery.BDWMKRService.getKRSuggestBySeedResponse retVal = ((WpfQuery.BDWMKRService.KRService)(this)).getKRSuggestBySeed(inValue);
            krSuggestResultTypes = retVal.krSuggestResultTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRSuggestBySeedResponse> WpfQuery.BDWMKRService.KRService.getKRSuggestBySeedAsync(WpfQuery.BDWMKRService.getKRSuggestBySeedRequest request) {
            return base.Channel.getKRSuggestBySeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRSuggestBySeedResponse> getKRSuggestBySeedAsync(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved) {
            WpfQuery.BDWMKRService.getKRSuggestBySeedRequest inValue = new WpfQuery.BDWMKRService.getKRSuggestBySeedRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seed = seed;
            inValue.groupId = groupId;
            inValue.regionList = regionList;
            inValue.targetType = targetType;
            inValue.aliveDays = aliveDays;
            inValue.packIds = packIds;
            inValue.reserved = reserved;
            return ((WpfQuery.BDWMKRService.KRService)(this)).getKRSuggestBySeedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.BDWMKRService.getKRAndSuggestBySeedResponse WpfQuery.BDWMKRService.KRService.getKRAndSuggestBySeed(WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest request) {
            return base.Channel.getKRAndSuggestBySeed(request);
        }
        
        public WpfQuery.BDWMKRService.ResHeader getKRAndSuggestBySeed(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved, out WpfQuery.BDWMKRService.KRResponse[] krResponses) {
            WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest inValue = new WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seed = seed;
            inValue.groupId = groupId;
            inValue.regionList = regionList;
            inValue.targetType = targetType;
            inValue.aliveDays = aliveDays;
            inValue.packIds = packIds;
            inValue.reserved = reserved;
            WpfQuery.BDWMKRService.getKRAndSuggestBySeedResponse retVal = ((WpfQuery.BDWMKRService.KRService)(this)).getKRAndSuggestBySeed(inValue);
            krResponses = retVal.krResponses;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRAndSuggestBySeedResponse> WpfQuery.BDWMKRService.KRService.getKRAndSuggestBySeedAsync(WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest request) {
            return base.Channel.getKRAndSuggestBySeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.BDWMKRService.getKRAndSuggestBySeedResponse> getKRAndSuggestBySeedAsync(WpfQuery.BDWMKRService.AuthHeader AuthHeader, string seed, long groupId, int[] regionList, int targetType, int aliveDays, int[] packIds, string reserved) {
            WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest inValue = new WpfQuery.BDWMKRService.getKRAndSuggestBySeedRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seed = seed;
            inValue.groupId = groupId;
            inValue.regionList = regionList;
            inValue.targetType = targetType;
            inValue.aliveDays = aliveDays;
            inValue.packIds = packIds;
            inValue.reserved = reserved;
            return ((WpfQuery.BDWMKRService.KRService)(this)).getKRAndSuggestBySeedAsync(inValue);
        }
    }
}
