//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuery.CreativeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v3", ConfigurationName="CreativeService.CreativeService")]
    public interface CreativeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/addCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.addCreativeResponse addCreative(WpfQuery.CreativeService.addCreativeRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/addCreative", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.addCreativeResponse> addCreativeAsync(WpfQuery.CreativeService.addCreativeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/updateCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.updateCreativeResponse updateCreative(WpfQuery.CreativeService.updateCreativeRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/updateCreative", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.updateCreativeResponse> updateCreativeAsync(WpfQuery.CreativeService.updateCreativeRequest request);
        
        // CODEGEN: 消息 activateCreativeRequest 的包装名称(activateCreativeRequest)以后生成的消息协定与默认值(activateCreative)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/activateCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.activateCreativeResponse activateCreative(WpfQuery.CreativeService.activateCreativeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/activateCreative", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.activateCreativeResponse> activateCreativeAsync(WpfQuery.CreativeService.activateCreativeRequest request);
        
        // CODEGEN: 消息 deleteCreativeRequest 的包装名称(deleteCreativeRequest)以后生成的消息协定与默认值(deleteCreative)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/deleteCreative", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.deleteCreativeResponse deleteCreative(WpfQuery.CreativeService.deleteCreativeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/deleteCreative", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.deleteCreativeResponse> deleteCreativeAsync(WpfQuery.CreativeService.deleteCreativeRequest request);
        
        // CODEGEN: 消息 getCreativeIdByAdgroupIdRequest 的包装名称(getCreativeIdByAdgroupIdRequest)以后生成的消息协定与默认值(getCreativeIdByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeIdByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.getCreativeIdByAdgroupIdResponse getCreativeIdByAdgroupId(WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeIdByAdgroupId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeIdByAdgroupIdResponse> getCreativeIdByAdgroupIdAsync(WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getCreativeByAdgroupIdRequest 的包装名称(getCreativeByAdgroupIdRequest)以后生成的消息协定与默认值(getCreativeByAdgroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeByAdgroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.getCreativeByAdgroupIdResponse getCreativeByAdgroupId(WpfQuery.CreativeService.getCreativeByAdgroupIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeByAdgroupId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeByAdgroupIdResponse> getCreativeByAdgroupIdAsync(WpfQuery.CreativeService.getCreativeByAdgroupIdRequest request);
        
        // CODEGEN: 消息 getCreativeByCreativeIdRequest 的包装名称(getCreativeByCreativeIdRequest)以后生成的消息协定与默认值(getCreativeByCreativeId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeByCreativeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.getCreativeByCreativeIdResponse getCreativeByCreativeId(WpfQuery.CreativeService.getCreativeByCreativeIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeByCreativeId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeByCreativeIdResponse> getCreativeByCreativeIdAsync(WpfQuery.CreativeService.getCreativeByCreativeIdRequest request);
        
        // CODEGEN: 消息 getCreativeStatusRequest 的包装名称(getCreativeStatusRequest)以后生成的消息协定与默认值(getCreativeStatus)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.getCreativeStatusResponse getCreativeStatus(WpfQuery.CreativeService.getCreativeStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeStatusResponse> getCreativeStatusAsync(WpfQuery.CreativeService.getCreativeStatusRequest request);
        
        // CODEGEN: 消息 getCreativeStatusZipRequest 的包装名称(getCreativeStatusZipRequest)以后生成的消息协定与默认值(getCreativeStatusZip)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeStatusZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.CreativeService.getCreativeStatusZipResponse getCreativeStatusZip(WpfQuery.CreativeService.getCreativeStatusZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/CreativeService/getCreativeStatusZip", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeStatusZipResponse> getCreativeStatusZipAsync(WpfQuery.CreativeService.getCreativeStatusZipRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        private string actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private long adgroupIdField;
        
        private long campaignIdField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class GroupCreative : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private CreativeType[] creativeTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CreativeType[] creativeTypes {
            get {
                return this.creativeTypesField;
            }
            set {
                this.creativeTypesField = value;
                this.RaisePropertyChanged("creativeTypes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class CreativeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long creativeIdField;
        
        private bool creativeIdFieldSpecified;
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private string titleField;
        
        private string description1Field;
        
        private string description2Field;
        
        private string pcDestinationUrlField;
        
        private string pcDisplayUrlField;
        
        private string mobileDestinationUrlField;
        
        private string mobileDisplayUrlField;
        
        private bool pauseField;
        
        private bool pauseFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private int devicePreferenceField;
        
        private bool devicePreferenceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long creativeId {
            get {
                return this.creativeIdField;
            }
            set {
                this.creativeIdField = value;
                this.RaisePropertyChanged("creativeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creativeIdSpecified {
            get {
                return this.creativeIdFieldSpecified;
            }
            set {
                this.creativeIdFieldSpecified = value;
                this.RaisePropertyChanged("creativeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description1 {
            get {
                return this.description1Field;
            }
            set {
                this.description1Field = value;
                this.RaisePropertyChanged("description1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string description2 {
            get {
                return this.description2Field;
            }
            set {
                this.description2Field = value;
                this.RaisePropertyChanged("description2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pcDestinationUrl {
            get {
                return this.pcDestinationUrlField;
            }
            set {
                this.pcDestinationUrlField = value;
                this.RaisePropertyChanged("pcDestinationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string pcDisplayUrl {
            get {
                return this.pcDisplayUrlField;
            }
            set {
                this.pcDisplayUrlField = value;
                this.RaisePropertyChanged("pcDisplayUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string mobileDestinationUrl {
            get {
                return this.mobileDestinationUrlField;
            }
            set {
                this.mobileDestinationUrlField = value;
                this.RaisePropertyChanged("mobileDestinationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string mobileDisplayUrl {
            get {
                return this.mobileDisplayUrlField;
            }
            set {
                this.mobileDisplayUrlField = value;
                this.RaisePropertyChanged("mobileDisplayUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool pause {
            get {
                return this.pauseField;
            }
            set {
                this.pauseField = value;
                this.RaisePropertyChanged("pause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pauseSpecified {
            get {
                return this.pauseFieldSpecified;
            }
            set {
                this.pauseFieldSpecified = value;
                this.RaisePropertyChanged("pauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int devicePreference {
            get {
                return this.devicePreferenceField;
            }
            set {
                this.devicePreferenceField = value;
                this.RaisePropertyChanged("devicePreference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool devicePreferenceSpecified {
            get {
                return this.devicePreferenceFieldSpecified;
            }
            set {
                this.devicePreferenceFieldSpecified = value;
                this.RaisePropertyChanged("devicePreferenceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class GroupCreativeId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private long[] creativeIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long[] creativeIds {
            get {
                return this.creativeIdsField;
            }
            set {
                this.creativeIdsField = value;
                this.RaisePropertyChanged("creativeIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class addCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.CreativeType[] creativeTypes;
        
        public addCreativeRequest() {
        }
        
        public addCreativeRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            this.AuthHeader = AuthHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class addCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.CreativeType[] creativeTypes;
        
        public addCreativeResponse() {
        }
        
        public addCreativeResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class updateCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.CreativeType[] creativeTypes;
        
        public updateCreativeRequest() {
        }
        
        public updateCreativeRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            this.AuthHeader = AuthHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class updateCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.CreativeType[] creativeTypes;
        
        public updateCreativeResponse() {
        }
        
        public updateCreativeResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class activateCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] creativeIds;
        
        public activateCreativeRequest() {
        }
        
        public activateCreativeRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds) {
            this.AuthHeader = AuthHeader;
            this.creativeIds = creativeIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class activateCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.CreativeType[] creativeTypes;
        
        public activateCreativeResponse() {
        }
        
        public activateCreativeResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCreativeRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class deleteCreativeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] creativeIds;
        
        public deleteCreativeRequest() {
        }
        
        public deleteCreativeRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds) {
            this.AuthHeader = AuthHeader;
            this.creativeIds = creativeIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCreativeResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class deleteCreativeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int result;
        
        public deleteCreativeResponse() {
        }
        
        public deleteCreativeResponse(WpfQuery.CreativeService.ResHeader ResHeader, int result) {
            this.ResHeader = ResHeader;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeIdByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeIdByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getCreativeIdByAdgroupIdRequest() {
        }
        
        public getCreativeIdByAdgroupIdRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeIdByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeIdByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupCreativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.GroupCreativeId[] groupCreativeIds;
        
        public getCreativeIdByAdgroupIdResponse() {
        }
        
        public getCreativeIdByAdgroupIdResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.GroupCreativeId[] groupCreativeIds) {
            this.ResHeader = ResHeader;
            this.groupCreativeIds = groupCreativeIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByAdgroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeByAdgroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adgroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adgroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getCreativeByAdgroupIdRequest() {
        }
        
        public getCreativeByAdgroupIdRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.adgroupIds = adgroupIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByAdgroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeByAdgroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupCreatives", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.GroupCreative[] groupCreatives;
        
        public getCreativeByAdgroupIdResponse() {
        }
        
        public getCreativeByAdgroupIdResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.GroupCreative[] groupCreatives) {
            this.ResHeader = ResHeader;
            this.groupCreatives = groupCreatives;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByCreativeIdRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeByCreativeIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] creativeIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTemp;
        
        public getCreativeByCreativeIdRequest() {
        }
        
        public getCreativeByCreativeIdRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds, int getTemp) {
            this.AuthHeader = AuthHeader;
            this.creativeIds = creativeIds;
            this.getTemp = getTemp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeByCreativeIdResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeByCreativeIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.CreativeType[] creativeTypes;
        
        public getCreativeByCreativeIdResponse() {
        }
        
        public getCreativeByCreativeIdResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            this.ResHeader = ResHeader;
            this.creativeTypes = creativeTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getCreativeStatusRequest() {
        }
        
        public getCreativeStatusRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("creativeStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.CreativeService.StatusType[] creativeStatus;
        
        public getCreativeStatusResponse() {
        }
        
        public getCreativeStatusResponse(WpfQuery.CreativeService.ResHeader ResHeader, WpfQuery.CreativeService.StatusType[] creativeStatus) {
            this.ResHeader = ResHeader;
            this.creativeStatus = creativeStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusZipRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeStatusZipRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public getCreativeStatusZipRequest() {
        }
        
        public getCreativeStatusZipRequest(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] ids, int type) {
            this.AuthHeader = AuthHeader;
            this.ids = ids;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreativeStatusZipResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getCreativeStatusZipResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.CreativeService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] creativeStatus;
        
        public getCreativeStatusZipResponse() {
        }
        
        public getCreativeStatusZipResponse(WpfQuery.CreativeService.ResHeader ResHeader, byte[] creativeStatus) {
            this.ResHeader = ResHeader;
            this.creativeStatus = creativeStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreativeServiceChannel : WpfQuery.CreativeService.CreativeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreativeServiceClient : System.ServiceModel.ClientBase<WpfQuery.CreativeService.CreativeService>, WpfQuery.CreativeService.CreativeService {
        
        public CreativeServiceClient() {
        }
        
        public CreativeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreativeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreativeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreativeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.addCreativeResponse WpfQuery.CreativeService.CreativeService.addCreative(WpfQuery.CreativeService.addCreativeRequest request) {
            return base.Channel.addCreative(request);
        }
        
        public WpfQuery.CreativeService.ResHeader addCreative(WpfQuery.CreativeService.AuthHeader AuthHeader, ref WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            WpfQuery.CreativeService.addCreativeRequest inValue = new WpfQuery.CreativeService.addCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeTypes = creativeTypes;
            WpfQuery.CreativeService.addCreativeResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).addCreative(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.addCreativeResponse> addCreativeAsync(WpfQuery.CreativeService.addCreativeRequest request) {
            return base.Channel.addCreativeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.updateCreativeResponse WpfQuery.CreativeService.CreativeService.updateCreative(WpfQuery.CreativeService.updateCreativeRequest request) {
            return base.Channel.updateCreative(request);
        }
        
        public WpfQuery.CreativeService.ResHeader updateCreative(WpfQuery.CreativeService.AuthHeader AuthHeader, ref WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            WpfQuery.CreativeService.updateCreativeRequest inValue = new WpfQuery.CreativeService.updateCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeTypes = creativeTypes;
            WpfQuery.CreativeService.updateCreativeResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).updateCreative(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.updateCreativeResponse> updateCreativeAsync(WpfQuery.CreativeService.updateCreativeRequest request) {
            return base.Channel.updateCreativeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.activateCreativeResponse WpfQuery.CreativeService.CreativeService.activateCreative(WpfQuery.CreativeService.activateCreativeRequest request) {
            return base.Channel.activateCreative(request);
        }
        
        public WpfQuery.CreativeService.ResHeader activateCreative(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds, out WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            WpfQuery.CreativeService.activateCreativeRequest inValue = new WpfQuery.CreativeService.activateCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            WpfQuery.CreativeService.activateCreativeResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).activateCreative(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.activateCreativeResponse> WpfQuery.CreativeService.CreativeService.activateCreativeAsync(WpfQuery.CreativeService.activateCreativeRequest request) {
            return base.Channel.activateCreativeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.activateCreativeResponse> activateCreativeAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds) {
            WpfQuery.CreativeService.activateCreativeRequest inValue = new WpfQuery.CreativeService.activateCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            return ((WpfQuery.CreativeService.CreativeService)(this)).activateCreativeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.deleteCreativeResponse WpfQuery.CreativeService.CreativeService.deleteCreative(WpfQuery.CreativeService.deleteCreativeRequest request) {
            return base.Channel.deleteCreative(request);
        }
        
        public WpfQuery.CreativeService.ResHeader deleteCreative(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds, out int result) {
            WpfQuery.CreativeService.deleteCreativeRequest inValue = new WpfQuery.CreativeService.deleteCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            WpfQuery.CreativeService.deleteCreativeResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).deleteCreative(inValue);
            result = retVal.result;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.deleteCreativeResponse> WpfQuery.CreativeService.CreativeService.deleteCreativeAsync(WpfQuery.CreativeService.deleteCreativeRequest request) {
            return base.Channel.deleteCreativeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.deleteCreativeResponse> deleteCreativeAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds) {
            WpfQuery.CreativeService.deleteCreativeRequest inValue = new WpfQuery.CreativeService.deleteCreativeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            return ((WpfQuery.CreativeService.CreativeService)(this)).deleteCreativeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.getCreativeIdByAdgroupIdResponse WpfQuery.CreativeService.CreativeService.getCreativeIdByAdgroupId(WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest request) {
            return base.Channel.getCreativeIdByAdgroupId(request);
        }
        
        public WpfQuery.CreativeService.ResHeader getCreativeIdByAdgroupId(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out WpfQuery.CreativeService.GroupCreativeId[] groupCreativeIds) {
            WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest inValue = new WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            WpfQuery.CreativeService.getCreativeIdByAdgroupIdResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeIdByAdgroupId(inValue);
            groupCreativeIds = retVal.groupCreativeIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeIdByAdgroupIdResponse> WpfQuery.CreativeService.CreativeService.getCreativeIdByAdgroupIdAsync(WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest request) {
            return base.Channel.getCreativeIdByAdgroupIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeIdByAdgroupIdResponse> getCreativeIdByAdgroupIdAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest inValue = new WpfQuery.CreativeService.getCreativeIdByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            return ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeIdByAdgroupIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.getCreativeByAdgroupIdResponse WpfQuery.CreativeService.CreativeService.getCreativeByAdgroupId(WpfQuery.CreativeService.getCreativeByAdgroupIdRequest request) {
            return base.Channel.getCreativeByAdgroupId(request);
        }
        
        public WpfQuery.CreativeService.ResHeader getCreativeByAdgroupId(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp, out WpfQuery.CreativeService.GroupCreative[] groupCreatives) {
            WpfQuery.CreativeService.getCreativeByAdgroupIdRequest inValue = new WpfQuery.CreativeService.getCreativeByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            WpfQuery.CreativeService.getCreativeByAdgroupIdResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeByAdgroupId(inValue);
            groupCreatives = retVal.groupCreatives;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeByAdgroupIdResponse> WpfQuery.CreativeService.CreativeService.getCreativeByAdgroupIdAsync(WpfQuery.CreativeService.getCreativeByAdgroupIdRequest request) {
            return base.Channel.getCreativeByAdgroupIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeByAdgroupIdResponse> getCreativeByAdgroupIdAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] adgroupIds, int getTemp) {
            WpfQuery.CreativeService.getCreativeByAdgroupIdRequest inValue = new WpfQuery.CreativeService.getCreativeByAdgroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adgroupIds = adgroupIds;
            inValue.getTemp = getTemp;
            return ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeByAdgroupIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.getCreativeByCreativeIdResponse WpfQuery.CreativeService.CreativeService.getCreativeByCreativeId(WpfQuery.CreativeService.getCreativeByCreativeIdRequest request) {
            return base.Channel.getCreativeByCreativeId(request);
        }
        
        public WpfQuery.CreativeService.ResHeader getCreativeByCreativeId(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds, int getTemp, out WpfQuery.CreativeService.CreativeType[] creativeTypes) {
            WpfQuery.CreativeService.getCreativeByCreativeIdRequest inValue = new WpfQuery.CreativeService.getCreativeByCreativeIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            inValue.getTemp = getTemp;
            WpfQuery.CreativeService.getCreativeByCreativeIdResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeByCreativeId(inValue);
            creativeTypes = retVal.creativeTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeByCreativeIdResponse> WpfQuery.CreativeService.CreativeService.getCreativeByCreativeIdAsync(WpfQuery.CreativeService.getCreativeByCreativeIdRequest request) {
            return base.Channel.getCreativeByCreativeIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeByCreativeIdResponse> getCreativeByCreativeIdAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] creativeIds, int getTemp) {
            WpfQuery.CreativeService.getCreativeByCreativeIdRequest inValue = new WpfQuery.CreativeService.getCreativeByCreativeIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.creativeIds = creativeIds;
            inValue.getTemp = getTemp;
            return ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeByCreativeIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.getCreativeStatusResponse WpfQuery.CreativeService.CreativeService.getCreativeStatus(WpfQuery.CreativeService.getCreativeStatusRequest request) {
            return base.Channel.getCreativeStatus(request);
        }
        
        public WpfQuery.CreativeService.ResHeader getCreativeStatus(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] ids, int type, out WpfQuery.CreativeService.StatusType[] creativeStatus) {
            WpfQuery.CreativeService.getCreativeStatusRequest inValue = new WpfQuery.CreativeService.getCreativeStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            WpfQuery.CreativeService.getCreativeStatusResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeStatus(inValue);
            creativeStatus = retVal.creativeStatus;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeStatusResponse> WpfQuery.CreativeService.CreativeService.getCreativeStatusAsync(WpfQuery.CreativeService.getCreativeStatusRequest request) {
            return base.Channel.getCreativeStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeStatusResponse> getCreativeStatusAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] ids, int type) {
            WpfQuery.CreativeService.getCreativeStatusRequest inValue = new WpfQuery.CreativeService.getCreativeStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            return ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.CreativeService.getCreativeStatusZipResponse WpfQuery.CreativeService.CreativeService.getCreativeStatusZip(WpfQuery.CreativeService.getCreativeStatusZipRequest request) {
            return base.Channel.getCreativeStatusZip(request);
        }
        
        public WpfQuery.CreativeService.ResHeader getCreativeStatusZip(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] ids, int type, out byte[] creativeStatus) {
            WpfQuery.CreativeService.getCreativeStatusZipRequest inValue = new WpfQuery.CreativeService.getCreativeStatusZipRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            WpfQuery.CreativeService.getCreativeStatusZipResponse retVal = ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeStatusZip(inValue);
            creativeStatus = retVal.creativeStatus;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeStatusZipResponse> WpfQuery.CreativeService.CreativeService.getCreativeStatusZipAsync(WpfQuery.CreativeService.getCreativeStatusZipRequest request) {
            return base.Channel.getCreativeStatusZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.CreativeService.getCreativeStatusZipResponse> getCreativeStatusZipAsync(WpfQuery.CreativeService.AuthHeader AuthHeader, long[] ids, int type) {
            WpfQuery.CreativeService.getCreativeStatusZipRequest inValue = new WpfQuery.CreativeService.getCreativeStatusZipRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ids = ids;
            inValue.type = type;
            return ((WpfQuery.CreativeService.CreativeService)(this)).getCreativeStatusZipAsync(inValue);
        }
    }
}
