//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuery.KRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/sms/v3", ConfigurationName="KRService.KRService")]
    public interface KRService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getAdGroupBySeedWords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getAdGroupBySeedWordsResponse getAdGroupBySeedWords(WpfQuery.KRService.getAdGroupBySeedWordsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getAdGroupBySeedWords", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getAdGroupBySeedWordsResponse> getAdGroupBySeedWordsAsync(WpfQuery.KRService.getAdGroupBySeedWordsRequest request);
        
        // CODEGEN: 消息 getKRbySeedWordRequest 的包装名称(getKRbySeedWordRequest)以后生成的消息协定与默认值(getKRbySeedWord)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRbySeedWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRbySeedWordResponse getKRbySeedWord(WpfQuery.KRService.getKRbySeedWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRbySeedWord", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRbySeedWordResponse> getKRbySeedWordAsync(WpfQuery.KRService.getKRbySeedWordRequest request);
        
        // CODEGEN: 消息 getKRFileIdbySeedWordRequest 的包装名称(getKRFileIdbySeedWordRequest)以后生成的消息协定与默认值(getKRFileIdbySeedWord)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRFileIdbySeedWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRFileIdbySeedWordResponse getKRFileIdbySeedWord(WpfQuery.KRService.getKRFileIdbySeedWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRFileIdbySeedWord", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRFileIdbySeedWordResponse> getKRFileIdbySeedWordAsync(WpfQuery.KRService.getKRFileIdbySeedWordRequest request);
        
        // CODEGEN: 消息 getKRFileStateRequest 的包装名称(getKRFileStateRequest)以后生成的消息协定与默认值(getKRFileState)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRFileState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRFileStateResponse getKRFileState(WpfQuery.KRService.getKRFileStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRFileState", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRFileStateResponse> getKRFileStateAsync(WpfQuery.KRService.getKRFileStateRequest request);
        
        // CODEGEN: 消息 getKRFilePathRequest 的包装名称(getKRFilePathRequest)以后生成的消息协定与默认值(getKRFilePath)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRFilePath", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRFilePathResponse getKRFilePath(WpfQuery.KRService.getKRFilePathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRFilePath", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRFilePathResponse> getKRFilePathAsync(WpfQuery.KRService.getKRFilePathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRQuota", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRQuotaResponse getKRQuota(WpfQuery.KRService.getKRQuotaRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRQuota", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRQuotaResponse> getKRQuotaAsync(WpfQuery.KRService.getKRQuotaRequest request);
        
        // CODEGEN: 消息 getKRbySeedUrlRequest 的包装名称(getKRbySeedUrlRequest)以后生成的消息协定与默认值(getKRbySeedUrl)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRbySeedUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRbySeedUrlResponse getKRbySeedUrl(WpfQuery.KRService.getKRbySeedUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRbySeedUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRbySeedUrlResponse> getKRbySeedUrlAsync(WpfQuery.KRService.getKRbySeedUrlRequest request);
        
        // CODEGEN: 消息 getSeedWordRequest 的包装名称(getSeedWordRequest)以后生成的消息协定与默认值(getSeedWord)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getSeedWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getSeedWordResponse getSeedWord(WpfQuery.KRService.getSeedWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getSeedWord", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getSeedWordResponse> getSeedWordAsync(WpfQuery.KRService.getSeedWordRequest request);
        
        // CODEGEN: 消息 getSeedUrlRequest 的包装名称(getSeedUrlRequest)以后生成的消息协定与默认值(getSeedUrl)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getSeedUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getSeedUrlResponse getSeedUrl(WpfQuery.KRService.getSeedUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getSeedUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getSeedUrlResponse> getSeedUrlAsync(WpfQuery.KRService.getSeedUrlRequest request);
        
        // CODEGEN: 消息 getKRCustomRequest 的包装名称(getKRCustomRequest)以后生成的消息协定与默认值(getKRCustom)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRCustomResponse getKRCustom(WpfQuery.KRService.getKRCustomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRCustom", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRCustomResponse> getKRCustomAsync(WpfQuery.KRService.getKRCustomRequest request);
        
        // CODEGEN: 消息 getKRByMultiSeedWordRequest 的包装名称(GetKRByMultiSeedWordRequest)以后生成的消息协定与默认值(getKRByMultiSeedWord)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRByMultiSeedWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.KRService.getKRByMultiSeedWordResponse getKRByMultiSeedWord(WpfQuery.KRService.getKRByMultiSeedWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/sms/v3/KRService/getKRByMultiSeedWord", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRByMultiSeedWordResponse> getKRByMultiSeedWordAsync(WpfQuery.KRService.getKRByMultiSeedWordRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        private string accessTokenField;
        
        private int account_typeField;
        
        private bool account_typeFieldSpecified;
        
        private string actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int account_type {
            get {
                return this.account_typeField;
            }
            set {
                this.account_typeField = value;
                this.RaisePropertyChanged("account_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool account_typeSpecified {
            get {
                return this.account_typeFieldSpecified;
            }
            set {
                this.account_typeFieldSpecified = value;
                this.RaisePropertyChanged("account_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class SeedUrl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string urlField;
        
        private string[] urlTagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("urlTag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] urlTag {
            get {
                return this.urlTagField;
            }
            set {
                this.urlTagField = value;
                this.RaisePropertyChanged("urlTag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class KRResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private long exactPVField;
        
        private bool exactPVFieldSpecified;
        
        private long phrasePVField;
        
        private bool phrasePVFieldSpecified;
        
        private long broadPVField;
        
        private bool broadPVFieldSpecified;
        
        private int competitionField;
        
        private int hotMonthField;
        
        private bool hotMonthFieldSpecified;
        
        private long hotMonthPVField;
        
        private bool hotMonthPVFieldSpecified;
        
        private string groupField;
        
        private int flag1Field;
        
        private bool flag1FieldSpecified;
        
        private int flag2Field;
        
        private bool flag2FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long exactPV {
            get {
                return this.exactPVField;
            }
            set {
                this.exactPVField = value;
                this.RaisePropertyChanged("exactPV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exactPVSpecified {
            get {
                return this.exactPVFieldSpecified;
            }
            set {
                this.exactPVFieldSpecified = value;
                this.RaisePropertyChanged("exactPVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long phrasePV {
            get {
                return this.phrasePVField;
            }
            set {
                this.phrasePVField = value;
                this.RaisePropertyChanged("phrasePV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool phrasePVSpecified {
            get {
                return this.phrasePVFieldSpecified;
            }
            set {
                this.phrasePVFieldSpecified = value;
                this.RaisePropertyChanged("phrasePVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long broadPV {
            get {
                return this.broadPVField;
            }
            set {
                this.broadPVField = value;
                this.RaisePropertyChanged("broadPV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool broadPVSpecified {
            get {
                return this.broadPVFieldSpecified;
            }
            set {
                this.broadPVFieldSpecified = value;
                this.RaisePropertyChanged("broadPVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int competition {
            get {
                return this.competitionField;
            }
            set {
                this.competitionField = value;
                this.RaisePropertyChanged("competition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int hotMonth {
            get {
                return this.hotMonthField;
            }
            set {
                this.hotMonthField = value;
                this.RaisePropertyChanged("hotMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hotMonthSpecified {
            get {
                return this.hotMonthFieldSpecified;
            }
            set {
                this.hotMonthFieldSpecified = value;
                this.RaisePropertyChanged("hotMonthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long hotMonthPV {
            get {
                return this.hotMonthPVField;
            }
            set {
                this.hotMonthPVField = value;
                this.RaisePropertyChanged("hotMonthPV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hotMonthPVSpecified {
            get {
                return this.hotMonthPVFieldSpecified;
            }
            set {
                this.hotMonthPVFieldSpecified = value;
                this.RaisePropertyChanged("hotMonthPVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int flag1 {
            get {
                return this.flag1Field;
            }
            set {
                this.flag1Field = value;
                this.RaisePropertyChanged("flag1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flag1Specified {
            get {
                return this.flag1FieldSpecified;
            }
            set {
                this.flag1FieldSpecified = value;
                this.RaisePropertyChanged("flag1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int flag2 {
            get {
                return this.flag2Field;
            }
            set {
                this.flag2Field = value;
                this.RaisePropertyChanged("flag2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flag2Specified {
            get {
                return this.flag2FieldSpecified;
            }
            set {
                this.flag2FieldSpecified = value;
                this.RaisePropertyChanged("flag2Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class SeedFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int matchTypeField;
        
        private bool matchTypeFieldSpecified;
        
        private string[] negativeWordField;
        
        private long pvLowField;
        
        private bool pvLowFieldSpecified;
        
        private long pvHighField;
        
        private bool pvHighFieldSpecified;
        
        private long competeLowField;
        
        private bool competeLowFieldSpecified;
        
        private long competeHighField;
        
        private bool competeHighFieldSpecified;
        
        private int[] searchRegionField;
        
        private bool regionExtendField;
        
        private bool regionExtendFieldSpecified;
        
        private int maxNumField;
        
        private bool maxNumFieldSpecified;
        
        private bool hotMonthField;
        
        private bool hotMonthFieldSpecified;
        
        private int monthFilterField;
        
        private bool monthFilterFieldSpecified;
        
        private bool removeDuplicateField;
        
        private bool removeDuplicateFieldSpecified;
        
        private long[] duplicateUIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int matchType {
            get {
                return this.matchTypeField;
            }
            set {
                this.matchTypeField = value;
                this.RaisePropertyChanged("matchType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool matchTypeSpecified {
            get {
                return this.matchTypeFieldSpecified;
            }
            set {
                this.matchTypeFieldSpecified = value;
                this.RaisePropertyChanged("matchTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("negativeWord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] negativeWord {
            get {
                return this.negativeWordField;
            }
            set {
                this.negativeWordField = value;
                this.RaisePropertyChanged("negativeWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long pvLow {
            get {
                return this.pvLowField;
            }
            set {
                this.pvLowField = value;
                this.RaisePropertyChanged("pvLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pvLowSpecified {
            get {
                return this.pvLowFieldSpecified;
            }
            set {
                this.pvLowFieldSpecified = value;
                this.RaisePropertyChanged("pvLowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long pvHigh {
            get {
                return this.pvHighField;
            }
            set {
                this.pvHighField = value;
                this.RaisePropertyChanged("pvHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pvHighSpecified {
            get {
                return this.pvHighFieldSpecified;
            }
            set {
                this.pvHighFieldSpecified = value;
                this.RaisePropertyChanged("pvHighSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long competeLow {
            get {
                return this.competeLowField;
            }
            set {
                this.competeLowField = value;
                this.RaisePropertyChanged("competeLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competeLowSpecified {
            get {
                return this.competeLowFieldSpecified;
            }
            set {
                this.competeLowFieldSpecified = value;
                this.RaisePropertyChanged("competeLowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long competeHigh {
            get {
                return this.competeHighField;
            }
            set {
                this.competeHighField = value;
                this.RaisePropertyChanged("competeHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competeHighSpecified {
            get {
                return this.competeHighFieldSpecified;
            }
            set {
                this.competeHighFieldSpecified = value;
                this.RaisePropertyChanged("competeHighSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchRegion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int[] searchRegion {
            get {
                return this.searchRegionField;
            }
            set {
                this.searchRegionField = value;
                this.RaisePropertyChanged("searchRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool regionExtend {
            get {
                return this.regionExtendField;
            }
            set {
                this.regionExtendField = value;
                this.RaisePropertyChanged("regionExtend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regionExtendSpecified {
            get {
                return this.regionExtendFieldSpecified;
            }
            set {
                this.regionExtendFieldSpecified = value;
                this.RaisePropertyChanged("regionExtendSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int maxNum {
            get {
                return this.maxNumField;
            }
            set {
                this.maxNumField = value;
                this.RaisePropertyChanged("maxNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxNumSpecified {
            get {
                return this.maxNumFieldSpecified;
            }
            set {
                this.maxNumFieldSpecified = value;
                this.RaisePropertyChanged("maxNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool hotMonth {
            get {
                return this.hotMonthField;
            }
            set {
                this.hotMonthField = value;
                this.RaisePropertyChanged("hotMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hotMonthSpecified {
            get {
                return this.hotMonthFieldSpecified;
            }
            set {
                this.hotMonthFieldSpecified = value;
                this.RaisePropertyChanged("hotMonthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int monthFilter {
            get {
                return this.monthFilterField;
            }
            set {
                this.monthFilterField = value;
                this.RaisePropertyChanged("monthFilter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthFilterSpecified {
            get {
                return this.monthFilterFieldSpecified;
            }
            set {
                this.monthFilterFieldSpecified = value;
                this.RaisePropertyChanged("monthFilterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool removeDuplicate {
            get {
                return this.removeDuplicateField;
            }
            set {
                this.removeDuplicateField = value;
                this.RaisePropertyChanged("removeDuplicate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool removeDuplicateSpecified {
            get {
                return this.removeDuplicateFieldSpecified;
            }
            set {
                this.removeDuplicateFieldSpecified = value;
                this.RaisePropertyChanged("removeDuplicateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("duplicateUIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public long[] duplicateUIds {
            get {
                return this.duplicateUIdsField;
            }
            set {
                this.duplicateUIdsField = value;
                this.RaisePropertyChanged("duplicateUIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/sms/v3")]
    public partial class AutoAdGroupResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adgroupIdField;
        
        private bool adgroupIdFieldSpecified;
        
        private string adgroupNameField;
        
        private bool isNewAdgroupField;
        
        private bool isNewAdgroupFieldSpecified;
        
        private string[] keywordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adgroupId {
            get {
                return this.adgroupIdField;
            }
            set {
                this.adgroupIdField = value;
                this.RaisePropertyChanged("adgroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adgroupIdSpecified {
            get {
                return this.adgroupIdFieldSpecified;
            }
            set {
                this.adgroupIdFieldSpecified = value;
                this.RaisePropertyChanged("adgroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adgroupName {
            get {
                return this.adgroupNameField;
            }
            set {
                this.adgroupNameField = value;
                this.RaisePropertyChanged("adgroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isNewAdgroup {
            get {
                return this.isNewAdgroupField;
            }
            set {
                this.isNewAdgroupField = value;
                this.RaisePropertyChanged("isNewAdgroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isNewAdgroupSpecified {
            get {
                return this.isNewAdgroupFieldSpecified;
            }
            set {
                this.isNewAdgroupFieldSpecified = value;
                this.RaisePropertyChanged("isNewAdgroupSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keywords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
                this.RaisePropertyChanged("keywords");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdGroupBySeedWordsRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdGroupBySeedWordsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adGroupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adGroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("seedWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seedWords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getAdGroupBySeedWordsRequest() {
        }
        
        public getAdGroupBySeedWordsRequest(WpfQuery.KRService.AuthHeader AuthHeader, long[] adGroupIds, string[] seedWords, int device) {
            this.AuthHeader = AuthHeader;
            this.adGroupIds = adGroupIds;
            this.seedWords = seedWords;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdGroupBySeedWordsResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getAdGroupBySeedWordsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("autoAdGroupResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.AutoAdGroupResult[] autoAdGroupResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionid;
        
        public getAdGroupBySeedWordsResponse() {
        }
        
        public getAdGroupBySeedWordsResponse(WpfQuery.KRService.ResHeader ResHeader, WpfQuery.KRService.AutoAdGroupResult[] autoAdGroupResults, string sessionid) {
            this.ResHeader = ResHeader;
            this.autoAdGroupResults = autoAdGroupResults;
            this.sessionid = sessionid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRbySeedWordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRbySeedWordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seedWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getKRbySeedWordRequest() {
        }
        
        public getKRbySeedWordRequest(WpfQuery.KRService.AuthHeader AuthHeader, string seedWord, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.seedWord = seedWord;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRbySeedWordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRbySeedWordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.KRResult[] krResult;
        
        public getKRbySeedWordResponse() {
        }
        
        public getKRbySeedWordResponse(WpfQuery.KRService.ResHeader ResHeader, WpfQuery.KRService.KRResult[] krResult) {
            this.ResHeader = ResHeader;
            this.krResult = krResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileIdbySeedWordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRFileIdbySeedWordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seedWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seedWords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getKRFileIdbySeedWordRequest() {
        }
        
        public getKRFileIdbySeedWordRequest(WpfQuery.KRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.seedWords = seedWords;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileIdbySeedWordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRFileIdbySeedWordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFileId;
        
        public getKRFileIdbySeedWordResponse() {
        }
        
        public getKRFileIdbySeedWordResponse(WpfQuery.KRService.ResHeader ResHeader, string krFileId) {
            this.ResHeader = ResHeader;
            this.krFileId = krFileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileStateRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRFileStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFileId;
        
        public getKRFileStateRequest() {
        }
        
        public getKRFileStateRequest(WpfQuery.KRService.AuthHeader AuthHeader, string krFileId) {
            this.AuthHeader = AuthHeader;
            this.krFileId = krFileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileStateResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRFileStateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isGenerated;
        
        public getKRFileStateResponse() {
        }
        
        public getKRFileStateResponse(WpfQuery.KRService.ResHeader ResHeader, int isGenerated) {
            this.ResHeader = ResHeader;
            this.isGenerated = isGenerated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFilePathRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRFilePathRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFileId;
        
        public getKRFilePathRequest() {
        }
        
        public getKRFilePathRequest(WpfQuery.KRService.AuthHeader AuthHeader, string krFileId) {
            this.AuthHeader = AuthHeader;
            this.krFileId = krFileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFilePathResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRFilePathResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filePath;
        
        public getKRFilePathResponse() {
        }
        
        public getKRFilePathResponse(WpfQuery.KRService.ResHeader ResHeader, string filePath) {
            this.ResHeader = ResHeader;
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRQuotaRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRQuotaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        public getKRQuotaRequest() {
        }
        
        public getKRQuotaRequest(WpfQuery.KRService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRQuotaResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRQuotaResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long remain;
        
        public getKRQuotaResponse() {
        }
        
        public getKRQuotaResponse(WpfQuery.KRService.ResHeader ResHeader, long total, long remain) {
            this.ResHeader = ResHeader;
            this.total = total;
            this.remain = remain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRbySeedUrlRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRbySeedUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getKRbySeedUrlRequest() {
        }
        
        public getKRbySeedUrlRequest(WpfQuery.KRService.AuthHeader AuthHeader, string url, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.url = url;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRbySeedUrlResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRbySeedUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.KRResult[] krResult;
        
        public getKRbySeedUrlResponse() {
        }
        
        public getKRbySeedUrlResponse(WpfQuery.KRService.ResHeader ResHeader, WpfQuery.KRService.KRResult[] krResult) {
            this.ResHeader = ResHeader;
            this.krResult = krResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSeedWordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getSeedWordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getSeedWordRequest() {
        }
        
        public getSeedWordRequest(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.id = id;
            this.type = type;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSeedWordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getSeedWordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seedWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seedWords;
        
        public getSeedWordResponse() {
        }
        
        public getSeedWordResponse(WpfQuery.KRService.ResHeader ResHeader, string[] seedWords) {
            this.ResHeader = ResHeader;
            this.seedWords = seedWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSeedUrlRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getSeedUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getSeedUrlRequest() {
        }
        
        public getSeedUrlRequest(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.id = id;
            this.type = type;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSeedUrlResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getSeedUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seedUrls", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedUrl[] seedUrls;
        
        public getSeedUrlResponse() {
        }
        
        public getSeedUrlResponse(WpfQuery.KRService.ResHeader ResHeader, WpfQuery.KRService.SeedUrl[] seedUrls) {
            this.ResHeader = ResHeader;
            this.seedUrls = seedUrls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRCustomRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRCustomRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getKRCustomRequest() {
        }
        
        public getKRCustomRequest(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.id = id;
            this.type = type;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRCustomResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRCustomResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.KRResult[] krResult;
        
        public getKRCustomResponse() {
        }
        
        public getKRCustomResponse(WpfQuery.KRService.ResHeader ResHeader, WpfQuery.KRService.KRResult[] krResult) {
            this.ResHeader = ResHeader;
            this.krResult = krResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKRByMultiSeedWordRequest", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRByMultiSeedWordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seedWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seedWords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.SeedFilter seedFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int device;
        
        public getKRByMultiSeedWordRequest() {
        }
        
        public getKRByMultiSeedWordRequest(WpfQuery.KRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            this.AuthHeader = AuthHeader;
            this.seedWords = seedWords;
            this.seedFilter = seedFilter;
            this.device = device;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKRByMultiSeedWordResponse", WrapperNamespace="https://api.baidu.com/sem/sms/v3", IsWrapped=true)]
    public partial class getKRByMultiSeedWordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public WpfQuery.KRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/sms/v3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.KRService.KRResult[] krResult;
        
        public getKRByMultiSeedWordResponse() {
        }
        
        public getKRByMultiSeedWordResponse(WpfQuery.KRService.ResHeader ResHeader, WpfQuery.KRService.KRResult[] krResult) {
            this.ResHeader = ResHeader;
            this.krResult = krResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KRServiceChannel : WpfQuery.KRService.KRService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KRServiceClient : System.ServiceModel.ClientBase<WpfQuery.KRService.KRService>, WpfQuery.KRService.KRService {
        
        public KRServiceClient() {
        }
        
        public KRServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KRServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KRServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getAdGroupBySeedWordsResponse WpfQuery.KRService.KRService.getAdGroupBySeedWords(WpfQuery.KRService.getAdGroupBySeedWordsRequest request) {
            return base.Channel.getAdGroupBySeedWords(request);
        }
        
        public WpfQuery.KRService.ResHeader getAdGroupBySeedWords(WpfQuery.KRService.AuthHeader AuthHeader, long[] adGroupIds, string[] seedWords, int device, out WpfQuery.KRService.AutoAdGroupResult[] autoAdGroupResults, out string sessionid) {
            WpfQuery.KRService.getAdGroupBySeedWordsRequest inValue = new WpfQuery.KRService.getAdGroupBySeedWordsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adGroupIds = adGroupIds;
            inValue.seedWords = seedWords;
            inValue.device = device;
            WpfQuery.KRService.getAdGroupBySeedWordsResponse retVal = ((WpfQuery.KRService.KRService)(this)).getAdGroupBySeedWords(inValue);
            autoAdGroupResults = retVal.autoAdGroupResults;
            sessionid = retVal.sessionid;
            return retVal.ResHeader;
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getAdGroupBySeedWordsResponse> getAdGroupBySeedWordsAsync(WpfQuery.KRService.getAdGroupBySeedWordsRequest request) {
            return base.Channel.getAdGroupBySeedWordsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRbySeedWordResponse WpfQuery.KRService.KRService.getKRbySeedWord(WpfQuery.KRService.getKRbySeedWordRequest request) {
            return base.Channel.getKRbySeedWord(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRbySeedWord(WpfQuery.KRService.AuthHeader AuthHeader, string seedWord, WpfQuery.KRService.SeedFilter seedFilter, int device, out WpfQuery.KRService.KRResult[] krResult) {
            WpfQuery.KRService.getKRbySeedWordRequest inValue = new WpfQuery.KRService.getKRbySeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWord = seedWord;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getKRbySeedWordResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRbySeedWord(inValue);
            krResult = retVal.krResult;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRbySeedWordResponse> WpfQuery.KRService.KRService.getKRbySeedWordAsync(WpfQuery.KRService.getKRbySeedWordRequest request) {
            return base.Channel.getKRbySeedWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRbySeedWordResponse> getKRbySeedWordAsync(WpfQuery.KRService.AuthHeader AuthHeader, string seedWord, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getKRbySeedWordRequest inValue = new WpfQuery.KRService.getKRbySeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWord = seedWord;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getKRbySeedWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRFileIdbySeedWordResponse WpfQuery.KRService.KRService.getKRFileIdbySeedWord(WpfQuery.KRService.getKRFileIdbySeedWordRequest request) {
            return base.Channel.getKRFileIdbySeedWord(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRFileIdbySeedWord(WpfQuery.KRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.KRService.SeedFilter seedFilter, int device, out string krFileId) {
            WpfQuery.KRService.getKRFileIdbySeedWordRequest inValue = new WpfQuery.KRService.getKRFileIdbySeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getKRFileIdbySeedWordResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRFileIdbySeedWord(inValue);
            krFileId = retVal.krFileId;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRFileIdbySeedWordResponse> WpfQuery.KRService.KRService.getKRFileIdbySeedWordAsync(WpfQuery.KRService.getKRFileIdbySeedWordRequest request) {
            return base.Channel.getKRFileIdbySeedWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRFileIdbySeedWordResponse> getKRFileIdbySeedWordAsync(WpfQuery.KRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getKRFileIdbySeedWordRequest inValue = new WpfQuery.KRService.getKRFileIdbySeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getKRFileIdbySeedWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRFileStateResponse WpfQuery.KRService.KRService.getKRFileState(WpfQuery.KRService.getKRFileStateRequest request) {
            return base.Channel.getKRFileState(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRFileState(WpfQuery.KRService.AuthHeader AuthHeader, string krFileId, out int isGenerated) {
            WpfQuery.KRService.getKRFileStateRequest inValue = new WpfQuery.KRService.getKRFileStateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            WpfQuery.KRService.getKRFileStateResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRFileState(inValue);
            isGenerated = retVal.isGenerated;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRFileStateResponse> WpfQuery.KRService.KRService.getKRFileStateAsync(WpfQuery.KRService.getKRFileStateRequest request) {
            return base.Channel.getKRFileStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRFileStateResponse> getKRFileStateAsync(WpfQuery.KRService.AuthHeader AuthHeader, string krFileId) {
            WpfQuery.KRService.getKRFileStateRequest inValue = new WpfQuery.KRService.getKRFileStateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            return ((WpfQuery.KRService.KRService)(this)).getKRFileStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRFilePathResponse WpfQuery.KRService.KRService.getKRFilePath(WpfQuery.KRService.getKRFilePathRequest request) {
            return base.Channel.getKRFilePath(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRFilePath(WpfQuery.KRService.AuthHeader AuthHeader, string krFileId, out string filePath) {
            WpfQuery.KRService.getKRFilePathRequest inValue = new WpfQuery.KRService.getKRFilePathRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            WpfQuery.KRService.getKRFilePathResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRFilePath(inValue);
            filePath = retVal.filePath;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRFilePathResponse> WpfQuery.KRService.KRService.getKRFilePathAsync(WpfQuery.KRService.getKRFilePathRequest request) {
            return base.Channel.getKRFilePathAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRFilePathResponse> getKRFilePathAsync(WpfQuery.KRService.AuthHeader AuthHeader, string krFileId) {
            WpfQuery.KRService.getKRFilePathRequest inValue = new WpfQuery.KRService.getKRFilePathRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            return ((WpfQuery.KRService.KRService)(this)).getKRFilePathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRQuotaResponse WpfQuery.KRService.KRService.getKRQuota(WpfQuery.KRService.getKRQuotaRequest request) {
            return base.Channel.getKRQuota(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRQuota(WpfQuery.KRService.AuthHeader AuthHeader, out long total, out long remain) {
            WpfQuery.KRService.getKRQuotaRequest inValue = new WpfQuery.KRService.getKRQuotaRequest();
            inValue.AuthHeader = AuthHeader;
            WpfQuery.KRService.getKRQuotaResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRQuota(inValue);
            total = retVal.total;
            remain = retVal.remain;
            return retVal.ResHeader;
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRQuotaResponse> getKRQuotaAsync(WpfQuery.KRService.getKRQuotaRequest request) {
            return base.Channel.getKRQuotaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRbySeedUrlResponse WpfQuery.KRService.KRService.getKRbySeedUrl(WpfQuery.KRService.getKRbySeedUrlRequest request) {
            return base.Channel.getKRbySeedUrl(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRbySeedUrl(WpfQuery.KRService.AuthHeader AuthHeader, string url, WpfQuery.KRService.SeedFilter seedFilter, int device, out WpfQuery.KRService.KRResult[] krResult) {
            WpfQuery.KRService.getKRbySeedUrlRequest inValue = new WpfQuery.KRService.getKRbySeedUrlRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.url = url;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getKRbySeedUrlResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRbySeedUrl(inValue);
            krResult = retVal.krResult;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRbySeedUrlResponse> WpfQuery.KRService.KRService.getKRbySeedUrlAsync(WpfQuery.KRService.getKRbySeedUrlRequest request) {
            return base.Channel.getKRbySeedUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRbySeedUrlResponse> getKRbySeedUrlAsync(WpfQuery.KRService.AuthHeader AuthHeader, string url, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getKRbySeedUrlRequest inValue = new WpfQuery.KRService.getKRbySeedUrlRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.url = url;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getKRbySeedUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getSeedWordResponse WpfQuery.KRService.KRService.getSeedWord(WpfQuery.KRService.getSeedWordRequest request) {
            return base.Channel.getSeedWord(request);
        }
        
        public WpfQuery.KRService.ResHeader getSeedWord(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device, out string[] seedWords) {
            WpfQuery.KRService.getSeedWordRequest inValue = new WpfQuery.KRService.getSeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getSeedWordResponse retVal = ((WpfQuery.KRService.KRService)(this)).getSeedWord(inValue);
            seedWords = retVal.seedWords;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getSeedWordResponse> WpfQuery.KRService.KRService.getSeedWordAsync(WpfQuery.KRService.getSeedWordRequest request) {
            return base.Channel.getSeedWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getSeedWordResponse> getSeedWordAsync(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getSeedWordRequest inValue = new WpfQuery.KRService.getSeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getSeedWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getSeedUrlResponse WpfQuery.KRService.KRService.getSeedUrl(WpfQuery.KRService.getSeedUrlRequest request) {
            return base.Channel.getSeedUrl(request);
        }
        
        public WpfQuery.KRService.ResHeader getSeedUrl(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device, out WpfQuery.KRService.SeedUrl[] seedUrls) {
            WpfQuery.KRService.getSeedUrlRequest inValue = new WpfQuery.KRService.getSeedUrlRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getSeedUrlResponse retVal = ((WpfQuery.KRService.KRService)(this)).getSeedUrl(inValue);
            seedUrls = retVal.seedUrls;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getSeedUrlResponse> WpfQuery.KRService.KRService.getSeedUrlAsync(WpfQuery.KRService.getSeedUrlRequest request) {
            return base.Channel.getSeedUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getSeedUrlResponse> getSeedUrlAsync(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getSeedUrlRequest inValue = new WpfQuery.KRService.getSeedUrlRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getSeedUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRCustomResponse WpfQuery.KRService.KRService.getKRCustom(WpfQuery.KRService.getKRCustomRequest request) {
            return base.Channel.getKRCustom(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRCustom(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device, out WpfQuery.KRService.KRResult[] krResult) {
            WpfQuery.KRService.getKRCustomRequest inValue = new WpfQuery.KRService.getKRCustomRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getKRCustomResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRCustom(inValue);
            krResult = retVal.krResult;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRCustomResponse> WpfQuery.KRService.KRService.getKRCustomAsync(WpfQuery.KRService.getKRCustomRequest request) {
            return base.Channel.getKRCustomAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRCustomResponse> getKRCustomAsync(WpfQuery.KRService.AuthHeader AuthHeader, long id, int type, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getKRCustomRequest inValue = new WpfQuery.KRService.getKRCustomRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getKRCustomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.KRService.getKRByMultiSeedWordResponse WpfQuery.KRService.KRService.getKRByMultiSeedWord(WpfQuery.KRService.getKRByMultiSeedWordRequest request) {
            return base.Channel.getKRByMultiSeedWord(request);
        }
        
        public WpfQuery.KRService.ResHeader getKRByMultiSeedWord(WpfQuery.KRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.KRService.SeedFilter seedFilter, int device, out WpfQuery.KRService.KRResult[] krResult) {
            WpfQuery.KRService.getKRByMultiSeedWordRequest inValue = new WpfQuery.KRService.getKRByMultiSeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            WpfQuery.KRService.getKRByMultiSeedWordResponse retVal = ((WpfQuery.KRService.KRService)(this)).getKRByMultiSeedWord(inValue);
            krResult = retVal.krResult;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.KRService.getKRByMultiSeedWordResponse> WpfQuery.KRService.KRService.getKRByMultiSeedWordAsync(WpfQuery.KRService.getKRByMultiSeedWordRequest request) {
            return base.Channel.getKRByMultiSeedWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.KRService.getKRByMultiSeedWordResponse> getKRByMultiSeedWordAsync(WpfQuery.KRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.KRService.SeedFilter seedFilter, int device) {
            WpfQuery.KRService.getKRByMultiSeedWordRequest inValue = new WpfQuery.KRService.getKRByMultiSeedWordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.seedFilter = seedFilter;
            inValue.device = device;
            return ((WpfQuery.KRService.KRService)(this)).getKRByMultiSeedWordAsync(inValue);
        }
    }
}
