//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuery.SgKRService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.sogou.com/sem/sms/v1", ConfigurationName="SgKRService.KRService")]
    public interface KRService {
        
        // CODEGEN: 消息 getKRBySeedWordsRequest 的包装名称(getKRBySeedWordsRequest)以后生成的消息协定与默认值(getKRBySeedWords)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRBySeedWords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.SgKRService.getKRBySeedWordsResponse getKRBySeedWords(WpfQuery.SgKRService.getKRBySeedWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRBySeedWords", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRBySeedWordsResponse> getKRBySeedWordsAsync(WpfQuery.SgKRService.getKRBySeedWordsRequest request);
        
        // CODEGEN: 消息 getKRFileIdRequest 的包装名称(getKRFileIdRequest)以后生成的消息协定与默认值(getKRFileId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRFileId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.SgKRService.getKRFileIdResponse getKRFileId(WpfQuery.SgKRService.getKRFileIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRFileId", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFileIdResponse> getKRFileIdAsync(WpfQuery.SgKRService.getKRFileIdRequest request);
        
        // CODEGEN: 消息 getKRFileStatusRequest 的包装名称(getKRFileStatusRequest)以后生成的消息协定与默认值(getKRFileStatus)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRFileStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.SgKRService.getKRFileStatusResponse getKRFileStatus(WpfQuery.SgKRService.getKRFileStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRFileStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFileStatusResponse> getKRFileStatusAsync(WpfQuery.SgKRService.getKRFileStatusRequest request);
        
        // CODEGEN: 消息 getKRFilePathRequest 的包装名称(getKRFilePathRequest)以后生成的消息协定与默认值(getKRFilePath)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRFilePath", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.SgKRService.getKRFilePathResponse getKRFilePath(WpfQuery.SgKRService.getKRFilePathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRFilePath", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFilePathResponse> getKRFilePathAsync(WpfQuery.SgKRService.getKRFilePathRequest request);
        
        // CODEGEN: 消息 getKRCustomRequest 的包装名称(getKRCustomRequest)以后生成的消息协定与默认值(getKRCustom)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfQuery.SgKRService.getKRCustomResponse getKRCustom(WpfQuery.SgKRService.getKRCustomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.sogou.com/sem/sms/v1/KRService/getKRCustom", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRCustomResponse> getKRCustomAsync(WpfQuery.SgKRService.getKRCustomRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentusernameField;
        
        private string agentpasswordField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string agentusername {
            get {
                return this.agentusernameField;
            }
            set {
                this.agentusernameField = value;
                this.RaisePropertyChanged("agentusername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string agentpassword {
            get {
                return this.agentpasswordField;
            }
            set {
                this.agentpasswordField = value;
                this.RaisePropertyChanged("agentpassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.sogou.com/sem/sms/v1")]
    public partial class KRResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private int broadPVField;
        
        private bool broadPVFieldSpecified;
        
        private int competitionField;
        
        private bool competitionFieldSpecified;
        
        private int[] flagsField;
        
        private string cpcPlanNameField;
        
        private string cpcGrpNameField;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int broadPV {
            get {
                return this.broadPVField;
            }
            set {
                this.broadPVField = value;
                this.RaisePropertyChanged("broadPV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool broadPVSpecified {
            get {
                return this.broadPVFieldSpecified;
            }
            set {
                this.broadPVFieldSpecified = value;
                this.RaisePropertyChanged("broadPVSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int competition {
            get {
                return this.competitionField;
            }
            set {
                this.competitionField = value;
                this.RaisePropertyChanged("competition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competitionSpecified {
            get {
                return this.competitionFieldSpecified;
            }
            set {
                this.competitionFieldSpecified = value;
                this.RaisePropertyChanged("competitionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flags", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int[] flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
                this.RaisePropertyChanged("flags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cpcPlanName {
            get {
                return this.cpcPlanNameField;
            }
            set {
                this.cpcPlanNameField = value;
                this.RaisePropertyChanged("cpcPlanName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cpcGrpName {
            get {
                return this.cpcGrpNameField;
            }
            set {
                this.cpcGrpNameField = value;
                this.RaisePropertyChanged("cpcGrpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class OptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringMapItemType[] optStringField;
        
        private IntMapItemType[] optIntField;
        
        private LongMapItemType[] optLongField;
        
        private FloatMapItemType[] optFloatField;
        
        private DoubleMapItemType[] optDoubleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optString", Order=0)]
        public StringMapItemType[] optString {
            get {
                return this.optStringField;
            }
            set {
                this.optStringField = value;
                this.RaisePropertyChanged("optString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optInt", Order=1)]
        public IntMapItemType[] optInt {
            get {
                return this.optIntField;
            }
            set {
                this.optIntField = value;
                this.RaisePropertyChanged("optInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optLong", Order=2)]
        public LongMapItemType[] optLong {
            get {
                return this.optLongField;
            }
            set {
                this.optLongField = value;
                this.RaisePropertyChanged("optLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optFloat", Order=3)]
        public FloatMapItemType[] optFloat {
            get {
                return this.optFloatField;
            }
            set {
                this.optFloatField = value;
                this.RaisePropertyChanged("optFloat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optDouble", Order=4)]
        public DoubleMapItemType[] optDouble {
            get {
                return this.optDoubleField;
            }
            set {
                this.optDoubleField = value;
                this.RaisePropertyChanged("optDouble");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class StringMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class IntMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class LongMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class FloatMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
    public partial class DoubleMapItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.sogou.com/sem/sms/v1")]
    public partial class SeedWordKRResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string seedWordField;
        
        private KRResultType[] krResultTypesField;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string seedWord {
            get {
                return this.seedWordField;
            }
            set {
                this.seedWordField = value;
                this.RaisePropertyChanged("seedWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("krResultTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public KRResultType[] krResultTypes {
            get {
                return this.krResultTypesField;
            }
            set {
                this.krResultTypesField = value;
                this.RaisePropertyChanged("krResultTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.sogou.com/sem/sms/v1")]
    public partial class FilterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] exclusiveWordsField;
        
        private string[] inclusiveWordsField;
        
        private int[] flagsField;
        
        private int pvField;
        
        private bool pvFieldSpecified;
        
        private int competitionField;
        
        private bool competitionFieldSpecified;
        
        private int maxNumField;
        
        private bool maxNumFieldSpecified;
        
        private bool includeRegionField;
        
        private bool includeRegionFieldSpecified;
        
        private OptType optField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exclusiveWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] exclusiveWords {
            get {
                return this.exclusiveWordsField;
            }
            set {
                this.exclusiveWordsField = value;
                this.RaisePropertyChanged("exclusiveWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inclusiveWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] inclusiveWords {
            get {
                return this.inclusiveWordsField;
            }
            set {
                this.inclusiveWordsField = value;
                this.RaisePropertyChanged("inclusiveWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flags", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int[] flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
                this.RaisePropertyChanged("flags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pv {
            get {
                return this.pvField;
            }
            set {
                this.pvField = value;
                this.RaisePropertyChanged("pv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pvSpecified {
            get {
                return this.pvFieldSpecified;
            }
            set {
                this.pvFieldSpecified = value;
                this.RaisePropertyChanged("pvSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int competition {
            get {
                return this.competitionField;
            }
            set {
                this.competitionField = value;
                this.RaisePropertyChanged("competition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competitionSpecified {
            get {
                return this.competitionFieldSpecified;
            }
            set {
                this.competitionFieldSpecified = value;
                this.RaisePropertyChanged("competitionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int maxNum {
            get {
                return this.maxNumField;
            }
            set {
                this.maxNumField = value;
                this.RaisePropertyChanged("maxNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxNumSpecified {
            get {
                return this.maxNumFieldSpecified;
            }
            set {
                this.maxNumFieldSpecified = value;
                this.RaisePropertyChanged("maxNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool includeRegion {
            get {
                return this.includeRegionField;
            }
            set {
                this.includeRegionField = value;
                this.RaisePropertyChanged("includeRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool includeRegionSpecified {
            get {
                return this.includeRegionFieldSpecified;
            }
            set {
                this.includeRegionFieldSpecified = value;
                this.RaisePropertyChanged("includeRegionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public OptType opt {
            get {
                return this.optField;
            }
            set {
                this.optField = value;
                this.RaisePropertyChanged("opt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRBySeedWordsRequest", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRBySeedWordsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seedWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seedWords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.SgKRService.FilterType filterType;
        
        public getKRBySeedWordsRequest() {
        }
        
        public getKRBySeedWordsRequest(WpfQuery.SgKRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.SgKRService.FilterType filterType) {
            this.AuthHeader = AuthHeader;
            this.seedWords = seedWords;
            this.filterType = filterType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRBySeedWordsResponse", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRBySeedWordsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.SgKRService.SeedWordKRResultType[] krResults;
        
        public getKRBySeedWordsResponse() {
        }
        
        public getKRBySeedWordsResponse(WpfQuery.SgKRService.ResHeader ResHeader, WpfQuery.SgKRService.SeedWordKRResultType[] krResults) {
            this.ResHeader = ResHeader;
            this.krResults = krResults;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileIdRequest", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRFileIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("seedWords", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] seedWords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.SgKRService.FilterType filterType;
        
        public getKRFileIdRequest() {
        }
        
        public getKRFileIdRequest(WpfQuery.SgKRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.SgKRService.FilterType filterType) {
            this.AuthHeader = AuthHeader;
            this.seedWords = seedWords;
            this.filterType = filterType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileIdResponse", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRFileIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFileId;
        
        public getKRFileIdResponse() {
        }
        
        public getKRFileIdResponse(WpfQuery.SgKRService.ResHeader ResHeader, string krFileId) {
            this.ResHeader = ResHeader;
            this.krFileId = krFileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileStatusRequest", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRFileStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFileId;
        
        public getKRFileStatusRequest() {
        }
        
        public getKRFileStatusRequest(WpfQuery.SgKRService.AuthHeader AuthHeader, string krFileId) {
            this.AuthHeader = AuthHeader;
            this.krFileId = krFileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFileStatusResponse", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRFileStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isGenerated;
        
        public getKRFileStatusResponse() {
        }
        
        public getKRFileStatusResponse(WpfQuery.SgKRService.ResHeader ResHeader, int isGenerated) {
            this.ResHeader = ResHeader;
            this.isGenerated = isGenerated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFilePathRequest", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRFilePathRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFileId;
        
        public getKRFilePathRequest() {
        }
        
        public getKRFilePathRequest(WpfQuery.SgKRService.AuthHeader AuthHeader, string krFileId) {
            this.AuthHeader = AuthHeader;
            this.krFileId = krFileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRFilePathResponse", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRFilePathResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string krFilePath;
        
        public getKRFilePathResponse() {
        }
        
        public getKRFilePathResponse(WpfQuery.SgKRService.ResHeader ResHeader, string krFilePath) {
            this.ResHeader = ResHeader;
            this.krFilePath = krFilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRCustomRequest", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRCustomRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.SgKRService.FilterType filterType;
        
        public getKRCustomRequest() {
        }
        
        public getKRCustomRequest(WpfQuery.SgKRService.AuthHeader AuthHeader, long id, int type, WpfQuery.SgKRService.FilterType filterType) {
            this.AuthHeader = AuthHeader;
            this.id = id;
            this.type = type;
            this.filterType = filterType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getKRCustomResponse", WrapperNamespace="https://api.sogou.com/sem/sms/v1", IsWrapped=true)]
    public partial class getKRCustomResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.sogou.com/sem/common/v1")]
        public WpfQuery.SgKRService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.sogou.com/sem/sms/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("krResults", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfQuery.SgKRService.KRResultType[] krResults;
        
        public getKRCustomResponse() {
        }
        
        public getKRCustomResponse(WpfQuery.SgKRService.ResHeader ResHeader, WpfQuery.SgKRService.KRResultType[] krResults) {
            this.ResHeader = ResHeader;
            this.krResults = krResults;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KRServiceChannel : WpfQuery.SgKRService.KRService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KRServiceClient : System.ServiceModel.ClientBase<WpfQuery.SgKRService.KRService>, WpfQuery.SgKRService.KRService {
        
        public KRServiceClient() {
        }
        
        public KRServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KRServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KRServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KRServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.SgKRService.getKRBySeedWordsResponse WpfQuery.SgKRService.KRService.getKRBySeedWords(WpfQuery.SgKRService.getKRBySeedWordsRequest request) {
            return base.Channel.getKRBySeedWords(request);
        }
        
        public WpfQuery.SgKRService.ResHeader getKRBySeedWords(WpfQuery.SgKRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.SgKRService.FilterType filterType, out WpfQuery.SgKRService.SeedWordKRResultType[] krResults) {
            WpfQuery.SgKRService.getKRBySeedWordsRequest inValue = new WpfQuery.SgKRService.getKRBySeedWordsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.filterType = filterType;
            WpfQuery.SgKRService.getKRBySeedWordsResponse retVal = ((WpfQuery.SgKRService.KRService)(this)).getKRBySeedWords(inValue);
            krResults = retVal.krResults;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRBySeedWordsResponse> WpfQuery.SgKRService.KRService.getKRBySeedWordsAsync(WpfQuery.SgKRService.getKRBySeedWordsRequest request) {
            return base.Channel.getKRBySeedWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRBySeedWordsResponse> getKRBySeedWordsAsync(WpfQuery.SgKRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.SgKRService.FilterType filterType) {
            WpfQuery.SgKRService.getKRBySeedWordsRequest inValue = new WpfQuery.SgKRService.getKRBySeedWordsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.filterType = filterType;
            return ((WpfQuery.SgKRService.KRService)(this)).getKRBySeedWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.SgKRService.getKRFileIdResponse WpfQuery.SgKRService.KRService.getKRFileId(WpfQuery.SgKRService.getKRFileIdRequest request) {
            return base.Channel.getKRFileId(request);
        }
        
        public WpfQuery.SgKRService.ResHeader getKRFileId(WpfQuery.SgKRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.SgKRService.FilterType filterType, out string krFileId) {
            WpfQuery.SgKRService.getKRFileIdRequest inValue = new WpfQuery.SgKRService.getKRFileIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.filterType = filterType;
            WpfQuery.SgKRService.getKRFileIdResponse retVal = ((WpfQuery.SgKRService.KRService)(this)).getKRFileId(inValue);
            krFileId = retVal.krFileId;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFileIdResponse> WpfQuery.SgKRService.KRService.getKRFileIdAsync(WpfQuery.SgKRService.getKRFileIdRequest request) {
            return base.Channel.getKRFileIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFileIdResponse> getKRFileIdAsync(WpfQuery.SgKRService.AuthHeader AuthHeader, string[] seedWords, WpfQuery.SgKRService.FilterType filterType) {
            WpfQuery.SgKRService.getKRFileIdRequest inValue = new WpfQuery.SgKRService.getKRFileIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.seedWords = seedWords;
            inValue.filterType = filterType;
            return ((WpfQuery.SgKRService.KRService)(this)).getKRFileIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.SgKRService.getKRFileStatusResponse WpfQuery.SgKRService.KRService.getKRFileStatus(WpfQuery.SgKRService.getKRFileStatusRequest request) {
            return base.Channel.getKRFileStatus(request);
        }
        
        public WpfQuery.SgKRService.ResHeader getKRFileStatus(WpfQuery.SgKRService.AuthHeader AuthHeader, string krFileId, out int isGenerated) {
            WpfQuery.SgKRService.getKRFileStatusRequest inValue = new WpfQuery.SgKRService.getKRFileStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            WpfQuery.SgKRService.getKRFileStatusResponse retVal = ((WpfQuery.SgKRService.KRService)(this)).getKRFileStatus(inValue);
            isGenerated = retVal.isGenerated;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFileStatusResponse> WpfQuery.SgKRService.KRService.getKRFileStatusAsync(WpfQuery.SgKRService.getKRFileStatusRequest request) {
            return base.Channel.getKRFileStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFileStatusResponse> getKRFileStatusAsync(WpfQuery.SgKRService.AuthHeader AuthHeader, string krFileId) {
            WpfQuery.SgKRService.getKRFileStatusRequest inValue = new WpfQuery.SgKRService.getKRFileStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            return ((WpfQuery.SgKRService.KRService)(this)).getKRFileStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.SgKRService.getKRFilePathResponse WpfQuery.SgKRService.KRService.getKRFilePath(WpfQuery.SgKRService.getKRFilePathRequest request) {
            return base.Channel.getKRFilePath(request);
        }
        
        public WpfQuery.SgKRService.ResHeader getKRFilePath(WpfQuery.SgKRService.AuthHeader AuthHeader, string krFileId, out string krFilePath) {
            WpfQuery.SgKRService.getKRFilePathRequest inValue = new WpfQuery.SgKRService.getKRFilePathRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            WpfQuery.SgKRService.getKRFilePathResponse retVal = ((WpfQuery.SgKRService.KRService)(this)).getKRFilePath(inValue);
            krFilePath = retVal.krFilePath;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFilePathResponse> WpfQuery.SgKRService.KRService.getKRFilePathAsync(WpfQuery.SgKRService.getKRFilePathRequest request) {
            return base.Channel.getKRFilePathAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRFilePathResponse> getKRFilePathAsync(WpfQuery.SgKRService.AuthHeader AuthHeader, string krFileId) {
            WpfQuery.SgKRService.getKRFilePathRequest inValue = new WpfQuery.SgKRService.getKRFilePathRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.krFileId = krFileId;
            return ((WpfQuery.SgKRService.KRService)(this)).getKRFilePathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfQuery.SgKRService.getKRCustomResponse WpfQuery.SgKRService.KRService.getKRCustom(WpfQuery.SgKRService.getKRCustomRequest request) {
            return base.Channel.getKRCustom(request);
        }
        
        public WpfQuery.SgKRService.ResHeader getKRCustom(WpfQuery.SgKRService.AuthHeader AuthHeader, long id, int type, WpfQuery.SgKRService.FilterType filterType, out WpfQuery.SgKRService.KRResultType[] krResults) {
            WpfQuery.SgKRService.getKRCustomRequest inValue = new WpfQuery.SgKRService.getKRCustomRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.filterType = filterType;
            WpfQuery.SgKRService.getKRCustomResponse retVal = ((WpfQuery.SgKRService.KRService)(this)).getKRCustom(inValue);
            krResults = retVal.krResults;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRCustomResponse> WpfQuery.SgKRService.KRService.getKRCustomAsync(WpfQuery.SgKRService.getKRCustomRequest request) {
            return base.Channel.getKRCustomAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfQuery.SgKRService.getKRCustomResponse> getKRCustomAsync(WpfQuery.SgKRService.AuthHeader AuthHeader, long id, int type, WpfQuery.SgKRService.FilterType filterType) {
            WpfQuery.SgKRService.getKRCustomRequest inValue = new WpfQuery.SgKRService.getKRCustomRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.id = id;
            inValue.type = type;
            inValue.filterType = filterType;
            return ((WpfQuery.SgKRService.KRService)(this)).getKRCustomAsync(inValue);
        }
    }
}
